#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "liuyun shi",
                "name":        "流雲使",
                "type":        "殺",
                "bonus":       89,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/liuyun.c",
        ]),
        ([
                "id":          "yu zu",
                "name":        "獄卒",
                "type":        "殺",
                "bonus":       110,
                "msg":        "",
                "object":      "/d/shaolin/npc/yu-zu.c",
        ]),
        ([
                "id":          "shanzei tou",
                "name":        "山賊頭",
                "type":        "殺",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/baituo/npc/shanzei3.c",
        ]),
        ([
                "id":          "lin pingzhi",
                "name":        "林平之",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/lin-pingzhi.c",
        ]),
        ([
                "id":          "liu zhengfeng",
                "name":        "劉正風",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/henshan/liu.c",
        ]),
        ([
                "id":          "dingyi shitai",
                "name":        "定逸師太",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/yi.c",
        ]),
        ([
                "id":          "dingxian shitai",
                "name":        "定閒師太",
                "type":        "殺",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/xian.c",
        ]),
        ([
                "id":          "tianmen daoren",
                "name":        "天門道人",
                "type":        "殺",
                "bonus":       66,
                "msg":        "",
                "object":      "/kungfu/class/taishan/tianmen.c",
        ]),
        ([
                "id":          "dingjing shitai",
                "name":        "定靜師太",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/jing.c",
        ]),
        ([
                "id":          "tubi weng",
                "name":        "禿筆翁",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/meizhuang/tubi.c",
        ]),
        ([
                "id":          "zhao banshan",
                "name":        "趙半山",
                "type":        "殺",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/zhao.c",
        ]),
        ([
                "id":          "yu yutong",
                "name":        "餘魚同",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/yu.c",
        ]),
        ([
                "id":          "wuchen daozhang",
                "name":        "無塵道長",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/wuchen.c",
        ]),
        ([
                "id":          "lu feiqing",
                "name":        "陸菲青",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/lu.c",
        ]),
        ([
                "id":          "huangmei dashi",
                "name":        "黃眉大師",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/monk.c",
        ]),
        ([
                "id":          "zhou botong",
                "name":        "周伯通",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/taohua/npc/zhou.c",
        ]),
        ([
                "id":          "zhou zhongying",
                "name":        "周仲英",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/zhou.c",
        ]),
        ([
                "id":          "huiyue shi",
                "name":        "輝月使",
                "type":        "殺",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/huiyue.c",
        ]),
        ([
                "id":          "mo da",
                "name":        "莫大",
                "type":        "殺",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/henshan/mo.c",
        ]),
        ([
                "id":          "dabei laoren",
                "name":        "大悲老人",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/yixing/npc/dabei.c",
        ]),
        ([
                "id":          "yuan ziyi",
                "name":        "袁紫衣",
                "type":        "殺",
                "bonus":       106,
                "msg":        "",
                "object":      "/d/henshan/npc/yuanziyi.c",
        ]),
        ([
                "id":          "miaofeng shi",
                "name":        "妙風使",
                "type":        "殺",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/miaofeng.c",
        ]),
        ([
                "id":          "qiu chuji",
                "name":        "丘處機",
                "type":        "殺",
                "bonus":       100,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/qiu.c",
        ]),
        ([
                "id":          "liu chuxuan",
                "name":        "劉處玄",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/liu.c",
        ]),
        ([
                "id":          "yin tianzheng",
                "name":        "殷天正",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/yintianzheng.c",
        ]),
        ([
                "id":          "yang xiao",
                "name":        "楊逍",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/yangxiao.c",
        ]),
        ([
                "id":          "xie xun",
                "name":        "謝遜",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/xiexun.c",
        ]),
        ([
                "id":          "fan yao",
                "name":        "範遙",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/fanyao.c",
        ]),
        ([
                "id":          "huangmei dashi",
                "name":        "黃眉大師",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/dali/npc/huangmei.c",
        ]),
        ([
                "id":          "taoshi xian",
                "name":        "桃實仙",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao6.c",
        ]),
        ([
                "id":          "taohua xian",
                "name":        "桃花仙",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao5.c",
        ]),
        ([
                "id":          "taoye xian",
                "name":        "桃葉仙",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao4.c",
        ]),
        ([
                "id":          "taozhi xian",
                "name":        "桃枝仙",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao3.c",
        ]),
        ([
                "id":          "taogan xian",
                "name":        "桃幹仙",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao2.c",
        ]),
        ([
                "id":          "taogen xian",
                "name":        "桃根仙",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao1.c",
        ]),
        ([
                "id":          "duo long",
                "name":        "多隆",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/beijing/npc/duolong.c",
        ]),
        ([
                "id":          "yin litin",
                "name":        "殷梨亭",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/wudang/yin.c",
        ]),
        ([
                "id":          "zhang songxi",
                "name":        "張松溪",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/wudang/xi.c",
        ]),
        ([
                "id":          "song yuanqiao",
                "name":        "宋遠橋",
                "type":        "殺",
                "bonus":       106,
                "msg":        "",
                "object":      "/kungfu/class/wudang/song.c",
        ]),
        ([
                "id":          "zhang cuishan",
                "name":        "張翠山",
                "type":        "殺",
                "bonus":       100,
                "msg":        "",
                "object":      "/kungfu/class/wudang/shan.c",
        ]),
        ([
                "id":          "mo shenggu",
                "name":        "莫聲谷",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/wudang/mo.c",
        ]),
        ([
                "id":          "ben yin",
                "name":        "本因",
                "type":        "殺",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/tianlongsi/benyin.c",
        ]),
        ([
                "id":          "ben xiang",
                "name":        "本相",
                "type":        "殺",
                "bonus":       100,
                "msg":        "",
                "object":      "/kungfu/class/tianlongsi/benxiang.c",
        ]),
        ([
                "id":          "wen cangsong",
                "name":        "聞蒼松",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/wensong.c",
        ]),
        ([
                "id":          "ben guan",
                "name":        "本觀",
                "type":        "殺",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/tianlongsi/benguan.c",
        ]),
        ([
                "id":          "ben can",
                "name":        "本參",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/tianlongsi/bencan.c",
        ]),
        ([
                "id":          "qu lingfeng",
                "name":        "曲三",
                "type":        "殺",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/taohua/qu.c",
        ]),
        ([
                "id":          "lu chengfeng",
                "name":        "陸乘風",
                "type":        "殺",
                "bonus":       106,
                "msg":        "",
                "object":      "/kungfu/class/taohua/lu.c",
        ]),
        ([
                "id":          "feng mofeng",
                "name":        "馮鐵匠",
                "type":        "殺",
                "bonus":       74,
                "msg":        "",
                "object":      "/kungfu/class/taohua/feng.c",
        ]),
        ([
                "id":          "xuannan dashi",
                "name":        "玄難大師",
                "type":        "殺",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xuan-nan.c",
        ]),
        ([
                "id":          "xuanku dashi",
                "name":        "玄苦大師",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xuan-ku.c",
        ]),
        ([
                "id":          "wang chuyi",
                "name":        "王處一",
                "type":        "殺",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/wangchuyi.c",
        ]),
        ([
                "id":          "tan chuduan",
                "name":        "譚處端",
                "type":        "殺",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/tan.c",
        ]),
        ([
                "id":          "xi zhanglao",
                "name":        "奚長老",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/xi.c",
        ]),
        ([
                "id":          "lu youjiao",
                "name":        "魯有腳",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/lu.c",
        ]),
        ([
                "id":          "liang zhanglao",
                "name":        "梁長老",
                "type":        "殺",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/liang.c",
        ]),
        ([
                "id":          "jian zhanglao",
                "name":        "簡長老",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/jian.c",
        ]),
        ([
                "id":          "zhou zhiruo",
                "name":        "周芷若",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/emei/zhou.c",
        ]),
        ([
                "id":          "duan yu",
                "name":        "段譽",
                "type":        "殺",
                "bonus":       106,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyu.c",
        ]),
        ([
                "id":          "miao renfeng",
                "name":        "苗人鳳",
                "type":        "殺",
                "bonus":       82,
                "msg":        "",
                "object":      "/d/shaolin/npc/miao.c",
        ]),
        ([
                "id":          "chen jialuo",
                "name":        "陳家洛",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/chen.c",
        ]),
        ([
                "id":          "yue nv",
                "name":        "越女",
                "type":        "殺",
                "bonus":       85,
                "msg":        "",
                "object":      "/d/hangzhou/npc/yuenv.c",
        ]),
        ([
                "id":          "yuan ziyi",
                "name":        "袁紫衣",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/henshan/npc/yuanziyi.c",
        ]),
        ([
                "id":          "murong longcheng",
                "name":        "慕容龍城",
                "type":        "殺",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/murong/longcheng.c",
        ]),
        ([
                "id":          "wei yixiao",
                "name":        "韋一笑",
                "type":        "殺",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/weiyixiao.c",
        ]),
        ([
                "id":          "zhuo bufan",
                "name":        "卓不凡",
                "type":        "殺",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/zhuo.c",
        ]),
        ([
                "id":          "linghu chong",
                "name":        "令狐沖",
                "type":        "殺",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/huashan/linghu.c",
        ]),
        ([
                "id":          "gao laozhe",
                "name":        "高老者",
                "type":        "殺",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/huashan/gao-laozhe.c",
        ]),
        ([
                "id":          "feng qingyang",
                "name":        "風清揚",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/huashan/feng.c",
        ]),
        ([
                "id":          "ai laozhe",
                "name":        "矮老者",
                "type":        "殺",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/huashan/ai-laozhe.c",
        ]),
        ([
                "id":          "hu yizhi",
                "name":        "胡逸之",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/hu/huyizhi.c",
        ]),
        ([
                "id":          "yang guo",
                "name":        "楊過",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/gumu/yang.c",
        ]),
        ([
                "id":          "chen jinnan",
                "name":        "陳近南",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/yunlong/chen.c",
        ]),
        ([
                "id":          "song yuanqiao",
                "name":        "宋遠橋",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/wudang/song.c",
        ]),
        ([
                "id":          "kurong",
                "name":        "枯榮大師",
                "type":        "殺",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/tianlongsi/kurong.c",
        ]),
        ([
                "id":          "lu chengfeng",
                "name":        "陸乘風",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/taohua/lu.c",
        ]),
        ([
                "id":          "xuanbei dashi",
                "name":        "玄悲大師",
                "type":        "殺",
                "bonus":       76,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xuan-bei.c",
        ]),
        ([
                "id":          "wuming laoseng",
                "name":        "無名老僧",
                "type":        "殺",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/wuming.c",
        ]),
        ([
                "id":          "kong jian",
                "name":        "空見",
                "type":        "殺",
                "bonus":       85,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/kong-jian.c",
        ]),
        ([
                "id":          "du nan",
                "name":        "渡難",
                "type":        "殺",
                "bonus":       85,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-nan.c",
        ]),
        ([
                "id":          "du jie",
                "name":        "渡劫",
                "type":        "殺",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-jie.c",
        ]),
        ([
                "id":          "du e",
                "name":        "渡厄",
                "type":        "殺",
                "bonus":       84,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-e.c",
        ]),
        ([
                "id":          "zhou botong",
                "name":        "周伯通",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/zhou.c",
        ]),
        ([
                "id":          "wang chongyang",
                "name":        "王重陽",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/wang.c",
        ]),
        ([
                "id":          "lin chaoying",
                "name":        "林朝英",
                "type":        "殺",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/gumu/lin.c",
        ]),
        ([
                "id":          "ma dayuan",
                "name":        "馬大元",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/ma.c",
        ]),
        ([
                "id":          "yideng dashi",
                "name":        "一燈大師",
                "type":        "殺",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/duan/yideng.c",
        ]),
        ([
                "id":          "duan zhengming",
                "name":        "段正明",
                "type":        "殺",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanzm.c",
        ]),
        ([
                "id":          "duan yu",
                "name":        "段譽",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyu.c",
        ]),
        ([
                "id":          "duan yanqing",
                "name":        "段延慶",
                "type":        "殺",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyq.c",
        ]),
});
mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
