#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "Yelv qi",
                "name":        "耶律齊",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/yelvqi.c",
        ]),
        ([
                "id":          "chi baicheng",
                "name":        "遲百城",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taishan/npc/chi.c",
        ]),
        ([
                "id":          "huangzhong gong",
                "name":        "黃鐘公",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/meizhuang/huang.c",
        ]),
        ([
                "id":          "ju jian",
                "name":        "菊劍",
                "type":        "殺",
                "bonus":       66,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/jujian.c",
        ]),
        ([
                "id":          "yi he",
                "name":        "儀和",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/he.c",
        ]),
        ([
                "id":          "ren ying ying",
                "name":        "任盈盈",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/heimuya/npc/obj/ren.c",
        ]),
        ([
                "id":          "gongye qian",
                "name":        "公冶乾",
                "type":        "殺",
                "bonus":       82,
                "msg":        "",
                "object":      "/d/yanziwu/npc/gongye.c",
        ]),
        ([
                "id":          "lan jian",
                "name":        "蘭劍",
                "type":        "殺",
                "bonus":       62,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/lanjian.c",
        ]),
        ([
                "id":          "tianmen daoren",
                "name":        "天門道人",
                "type":        "殺",
                "bonus":       100,
                "msg":        "",
                "object":      "/kungfu/class/taishan/tianmen.c",
        ]),
        ([
                "id":          "lu lianrong",
                "name":        "魯連榮",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/henshan/lu.c",
        ]),
        ([
                "id":          "ren yingying",
                "name":        "任盈盈",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/heimuya/npc/ren.c",
        ]),
        ([
                "id":          "fu mingyi",
                "name":        "符敏儀",
                "type":        "殺",
                "bonus":       62,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/fumingyi.c",
        ]),
        ([
                "id":          "feng boe",
                "name":        "風波惡",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/yanziwu/npc/feng.c",
        ]),
        ([
                "id":          "huang zhen",
                "name":        "黃真",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/xiangyang/npc/huangzhen.c",
        ]),
        ([
                "id":          "yi zhi",
                "name":        "儀質",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/zhi.c",
        ]),
        ([
                "id":          "ren ying ying",
                "name":        "任盈盈",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/heimuya/npc/ren1.c",
        ]),
        ([
                "id":          "zhao banshan",
                "name":        "趙半山",
                "type":        "殺",
                "bonus":       100,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/zhao.c",
        ]),
        ([
                "id":          "chang bozhi",
                "name":        "常伯志",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/chang2.c",
        ]),
        ([
                "id":          "chang hezhi",
                "name":        "常赫志",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/chang1.c",
        ]),
        ([
                "id":          "yi qing",
                "name":        "儀清",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/qing.c",
        ]),
        ([
                "id":          "deng baichuan",
                "name":        "鄧百川",
                "type":        "殺",
                "bonus":       95,
                "msg":        "",
                "object":      "/d/yanziwu/npc/deng.c",
        ]),
        ([
                "id":          "huiyue shi",
                "name":        "輝月使",
                "type":        "殺",
                "bonus":       100,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/huiyue.c",
        ]),
        ([
                "id":          "zhu jian",
                "name":        "竹劍",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/zhujian.c",
        ]),
        ([
                "id":          "wen tailai",
                "name":        "文泰來",
                "type":        "殺",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/wen.c",
        ]),
        ([
                "id":          "huo qingtong",
                "name":        "霍青桐",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/huo.c",
        ]),
        ([
                "id":          "bao butong",
                "name":        "包不同",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/yanziwu/npc/bao.c",
        ]),
        ([
                "id":          "mu wanqing",
                "name":        "木婉清",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/mu.c",
        ]),
        ([
                "id":          "miaofeng shi",
                "name":        "妙風使",
                "type":        "殺",
                "bonus":       100,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/miaofeng.c",
        ]),
        ([
                "id":          "nv lang",
                "name":        "蒙面女郎",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/lingjiu/npc/nvlang.c",
        ]),
        ([
                "id":          "sun buer",
                "name":        "孫不二",
                "type":        "殺",
                "bonus":       86,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/sun.c",
        ]),
        ([
                "id":          "hao datong",
                "name":        "郝大通",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/hao.c",
        ]),
        ([
                "id":          "mei jian",
                "name":        "梅劍",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/meijian.c",
        ]),
        ([
                "id":          "yue wife",
                "name":        "嶽夫人",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/kungfu/class/huashan/yue-wife.c",
        ]),
/*
        ([
                "id":          "guxu daozhang",
                "name":        "谷虛道長",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/wudang/guxu.c",
        ]),
*/
        ([
                "id":          "yu hongxing",
                "name":        "餘洪興",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/yu-hx.c",
        ]),
        ([
                "id":          "quan guanqing",
                "name":        "全冠清",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/quan-gq.c",
        ]),
        ([
                "id":          "li sheng",
                "name":        "黎生",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/li-sh.c",
        ]),
        ([
                "id":          "jingxuan shitai",
                "name":        "靜玄師太",
                "type":        "殺",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/emei/xuan.c",
        ]),
        ([
                "id":          "jingxu shitai",
                "name":        "靜虛師太",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/emei/xu.c",
        ]),
        ([
                "id":          "dao baifeng",
                "name":        "刀白鳳",
                "type":        "殺",
                "bonus":       62,
                "msg":        "",
                "object":      "/kungfu/class/duan/daobf.c",
        ]),
        ([
                "id":          "hua hegen",
                "name":        "華赫艮",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/dali/huahegen.c",
        ]),
        ([
                "id":          "gao shengtai",
                "name":        "高升泰",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/kungfu/class/dali/gaoshengtai.c",
        ]),
        ([
                "id":          "fan ye",
                "name":        "範驊",
                "type":        "殺",
                "bonus":       66,
                "msg":        "",
                "object":      "/kungfu/class/dali/fanye.c",
        ]),
        ([
                "id":          "ba tianshi",
                "name":        "巴天石",
                "type":        "殺",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/dali/batianshi.c",
        ]),
});
mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
