#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "yaochu",
                "name":        "藥鋤",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/yaochu.c",
        ]),
        ([
                "id":          "piqiu",
                "name":        "皮裘",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/guanwai/npc/obj/piqiu.c",
        ]),
        ([
                "id":          "card3",
                "name":        "青龍堂令牌",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/card3.c",
        ]),
        ([
                "id":          "cai dao",
                "name":        "菜刀",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/foshan/npc/obj/caidao.c",
        ]),
        ([
                "id":          "pink cloth",
                "name":        "粉紅綢衫",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/pink_cloth.c",
        ]),
        ([
                "id":          "jin duan",
                "name":        "錦緞",
                "type":        "尋",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/quanzhen/npc/obj/jinduan.c",
        ]),
        ([
                "id":          "blade",
                "name":        "鋼刀",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/quanzhen/npc/obj/gangdao.c",
        ]),
        ([
                "id":          "mu tang",
                "name":        "木鏜",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/mingjiao/obj/mutang.c",
        ]),
        ([
                "id":          "tie qiao",
                "name":        "鐵鍬",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/tieqiao.c",
        ]),
        ([
                "id":          "fenshui ci",
                "name":        "分水刺",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/fenshuici.c",
        ]),
        ([
                "id":          "golden necklace",
                "name":        "金項鍊",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/necklace.c",
        ]),
        ([
                "id":          "junfu",
                "name":        "軍服",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/quanzhen/npc/obj/junfu.c",
        ]),
        ([
                "id":          "Shui kao",
                "name":        "夜行水靠",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/shuikao.c",
        ]),
        ([
                "id":          "futou",
                "name":        "大斧頭",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/futou.c",
        ]),
        ([
                "id":          "sangmen fu",
                "name":        "喪門斧",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/axe.c",
        ]),
        ([
                "id":          "golden ring",
                "name":        "金戒指",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/goldring.c",
        ]),
        ([
                "id":          "blade",
                "name":        "鋼刀",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/xiaoyao/npc/obj/blade.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "黃布袈裟",
                "type":        "尋",
                "bonus":       70,
                "msg1":        "",
                "object":      "/d/shaolin/obj/xu-cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "青布僧衣",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/shaolin/obj/cloth.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "金邊黑布袈裟",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/shaolin/obj/cheng-cloth.c",
        ]),
        ([
                "id":          "changjian",
                "name":        "長劍",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/changjian.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "布衣",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/xiaoyao/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "[1;36m淺藍色馬褂[2;37;0m",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/cloth.c",
        ]),
        ([
                "id":          "yayi cloth",
                "name":        "衙役服",
                "type":        "尋",
                "bonus":       53,
                "msg1":        "",
                "object":      "/d/suzhou/npc/obj/yayifu.c",
        ]),
        ([
                "id":          "green cloth",
                "name":        "翠綠綢衫",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/green_cloth.c",
        ]),
        ([
                "id":          "flower shoes",
                "name":        "繡花小鞋",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/flower_shoe.c",
        ]),
        ([
                "id":          "mini-ao",
                "name":        "[34m綵緞緊身襖[2;37;0m",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/mini-dress.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "白布黑邊袈裟",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/shaolin/obj/qing-cloth.c",
        ]),
        ([
                "id":          "xiao ao",
                "name":        "圓領小襖",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/xiaoao.c",
        ]),
        ([
                "id":          "bai yi",
                "name":        "白衣",
                "type":        "尋",
                "bonus":       51,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/whitecloth.c",
        ]),
        ([
                "id":          "chang qun",
                "name":        "烏夷長裙",
                "type":        "尋",
                "bonus":       51,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/wchangqun.c",
        ]),
        ([
                "id":          "tou jin",
                "name":        "臺夷頭巾",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/ttoujin.c",
        ]),
        ([
                "id":          "junfu",
                "name":        "黃衣軍服",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/junfu.c",
        ]),
        ([
                "id":          "junfu",
                "name":        "軍服",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/city/obj/junfu.c",
        ]),
        ([
                "id":          "jitui",
                "name":        "烤雞腿",
                "type":        "尋",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/city/obj/jitui.c",
        ]),
        ([
                "id":          "changjian",
                "name":        "長劍",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/city/obj/changjian.c",
        ]),
        ([
                "id":          "yayi cloth",
                "name":        "衙役服",
                "type":        "尋",
                "bonus":       53,
                "msg1":        "",
                "object":      "/d/city/npc/obj/yayifu.c",
        ]),
        ([
                "id":          "pink cloth",
                "name":        "粉紅綢衫",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/city/npc/obj/pink_cloth.c",
        ]),
        ([
                "id":          "golden necklace",
                "name":        "金項鍊",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/city/npc/obj/necklace.c",
        ]),
        ([
                "id":          "blade",
                "name":        "鋼刀",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/city/npc/obj/gangdao.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "布衣",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/city/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "兵服",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/bingfu.c",
        ]),
        ([
                "id":          "key",
                "name":        "鑰匙",
                "type":        "尋",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/baituo/obj/key.c",
        ]),
});

mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
