#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "abi",
                "name":        "阿碧",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/yanziwu/npc/abi.c",
        ]),
        ([
                "id":          "jin xier",
                "name":        "進喜兒",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/xier.c",
        ]),
        ([
                "id":          "caishi ren",
                "name":        "採石人",
                "type":        "殺",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/huanghe/npc/caishiren.c",
        ]),
        ([
                "id":          "piao you",
                "name":        "票友",
                "type":        "殺",
                "bonus":       76,
                "msg":        "",
                "object":      "/d/suzhou/npc/piaoyou.c",
        ]),
        ([
                "id":          "zhangyuan",
                "name":        "掌園道長",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/quanzhen/npc/zhangyuan.c",
        ]),
        ([
                "id":          "zheng biaotou",
                "name":        "鄭鏢頭",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/fuzhou/npc/zheng.c",
        ]),
        ([
                "id":          "shi biaotou",
                "name":        "史鏢頭",
                "type":        "殺",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/fuzhou/npc/shi.c",
        ]),
        ([
                "id":          "geshiha",
                "name":        "戈什哈",
                "type":        "殺",
                "bonus":       86,
                "msg":        "",
                "object":      "/d/fuzhou/npc/geshiha.c",
        ]),
        ([
                "id":          "cui biaotou",
                "name":        "崔鏢頭",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/fuzhou/npc/cui.c",
        ]),
        ([
                "id":          "zhong sisao",
                "name":        "鍾四嫂",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/foshan/npc/zhongsisao.c",
        ]),
        ([
                "id":          "azhu",
                "name":        "阿朱",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/yanziwu/npc/azhu.c",
        ]),
        ([
                "id":          "alamuhan",
                "name":        "阿拉木罕",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/xingxiu/npc/alamuhan.c",
        ]),
        ([
                "id":          "seng ren",
                "name":        "遊方和尚",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/taishan/npc/seng-ren.c",
        ]),
        ([
                "id":          "huogong",
                "name":        "火工道人",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/quanzhen/npc/huogong.c",
        ]),
        ([
                "id":          "xixia bing",
                "name":        "西夏兵",
                "type":        "殺",
                "bonus":       73,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xixiabing.c",
        ]),
        ([
                "id":          "lao daoshi",
                "name":        "老道士",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/lingzhou/npc/laodaoshi.c",
        ]),
        ([
                "id":          "mengmianren",
                "name":        "蒙面人",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/hangzhou/npc/mengmian.c",
        ]),
        ([
                "id":          "zhuoma",
                "name":        "卓瑪",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/xuedao/npc/zhuoma.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "小沙彌",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/xiaoshami.c",
        ]),
        ([
                "id":          "saodi seng",
                "name":        "掃地僧",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/shaolin/npc/saodi-seng.c",
        ]),
        ([
                "id":          "zhanggui",
                "name":        "掌櫃",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hanzhong/npc/zhanggui.c",
        ]),
        ([
                "id":          "youfang daoren",
                "name":        "遊方道人",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/quanzhen/npc/youfang.c",
        ]),
        ([
                "id":          "yangzong",
                "name":        "央宗",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/xuedao/npc/yangzong.c",
        ]),
        ([
                "id":          "datie seng",
                "name":        "打鐵僧",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/shaolin/npc/datie-seng.c",
        ]),
        ([
                "id":          "lao heshang",
                "name":        "老和尚",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/hangzhou/npc/seng.c",
        ]),
        ([
                "id":          "bosi shangren",
                "name":        "波斯商人",
                "type":        "殺",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/xingxiu/npc/trader.c",
        ]),
        ([
                "id":          "song bing",
                "name":        "宋兵",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/xiangyang/npc/bing.c",
        ]),
        ([
                "id":          "saodi seng",
                "name":        "掃地僧",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/saodiseng.c",
        ]),
        ([
                "id":          "cheng ying",
                "name":        "程英",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/taohua/npc/cheng.c",
        ]),
        ([
                "id":          "xingzhe",
                "name":        "行者",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/shaolin/npc/xingzhe.c",
        ]),
        ([
                "id":          "zhike daozhang",
                "name":        "知客道長",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/quanzhen/npc/zhike.c",
        ]),
        ([
                "id":          "guan bing",
                "name":        "官兵",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/xingxiu/npc/bing.c",
        ]),
        ([
                "id":          "yu zu",
                "name":        "獄卒",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/shaolin/npc/yu-zu.c",
        ]),
        ([
                "id":          "xixia bing",
                "name":        "西夏兵",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/huanghe/npc/xixiabing.c",
        ]),
        ([
                "id":          "hong hua",
                "name":        "綠營會眾",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/hangzhou/npc/honghua2.c",
        ]),
        ([
                "id":          "hong hua",
                "name":        "紅花會眾",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/hangzhou/npc/honghua1.c",
        ]),
        ([
                "id":          "seng bing",
                "name":        "守寺僧兵",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/shaolin/npc/seng-bing3.c",
        ]),
        ([
                "id":          "da han",
                "name":        "大漢",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/mingjiao/npc/menwei1.c",
        ]),
        ([
                "id":          "qiao fu",
                "name":        "樵夫",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/huanghe/npc/qiaofu.c",
        ]),
        ([
                "id":          "pihuo shang",
                "name":        "皮貨商",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/guanwai/npc/pihuoshang.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "鏢頭",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/xiangyang/npc/biaotou.c",
        ]),
        ([
                "id":          "ya yi",
                "name":        "衙役",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/suzhou/npc/yayi.c",
        ]),
        ([
                "id":          "guan bing",
                "name":        "官兵",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/hanzhong/npc/bing.c",
        ]),
        ([
                "id":          "jieyin shi",
                "name":        "接引使",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/mingjiao/npc/jieyinshi.c",
        ]),
        ([
                "id":          "liu qin",
                "name":        "劉芹",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/henshan/npc/liuqin.c",
        ]),
        ([
                "id":          "lai fuer",
                "name":        "來福兒",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/fuer.c",
        ]),
        ([
                "id":          "zhangjing",
                "name":        "掌經道長",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/quanzhen/npc/zhangjing.c",
        ]),
        ([
                "id":          "hou yuanwai",
                "name":        "侯員外",
                "type":        "殺",
                "bonus":       73,
                "msg":        "",
                "object":      "/d/hanzhong/npc/yuanwai.c",
        ]),
        ([
                "id":          "yu fu",
                "name":        "漁夫",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/yufu.c",
        ]),
        ([
                "id":          "yangcan nu",
                "name":        "養蠶女",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/yangcannu.c",
        ]),
        ([
                "id":          "wuliang dizi",
                "name":        "無量劍弟子",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/wuliangdizi.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "烏夷商販",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/wshangfan.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "黃衣衛士",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/weishi1.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "素衣衛士",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/weishi.c",
        ]),
        ([
                "id":          "tai jian",
                "name":        "太監",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/taijian.c",
        ]),
        ([
                "id":          "shi zhe",
                "name":        "侍者",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/shizhe.c",
        ]),
        ([
                "id":          "shi cong",
                "name":        "侍從",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/dali/npc/shicong.c",
        ]),
        ([
                "id":          "shennong dizi",
                "name":        "神農幫弟子",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/shennongdizi.c",
        ]),
        ([
                "id":          "shao nu",
                "name":        "少女",
                "type":        "殺",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/shaonu.c",
        ]),
        ([
                "id":          "seng ren",
                "name":        "僧人",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/dali/npc/seng.c",
        ]),
        ([
                "id":          "lie ren",
                "name":        "臺夷獵人",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/dali/npc/lieshou.c",
        ]),
        ([
                "id":          "lie ren",
                "name":        "獵人",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/lieren.c",
        ]),
        ([
                "id":          "ke shang",
                "name":        "盛皮羅客商",
                "type":        "殺",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/keshang.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "家丁",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/jiading.c",
        ]),
        ([
                "id":          "yanghua nu",
                "name":        "養花女",
                "type":        "殺",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/huanu.c",
        ]),
        ([
                "id":          "gu niang",
                "name":        "臺夷姑娘",
                "type":        "殺",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/guniang.c",
        ]),
        ([
                "id":          "gong nu",
                "name":        "宮女",
                "type":        "殺",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/gongnu.c",
        ]),
        ([
                "id":          "girl",
                "name":        "擺夷女子",
                "type":        "殺",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/girl.c",
        ]),
        ([
                "id":          "caisang nv",
                "name":        "採桑女",
                "type":        "殺",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/caisangnu.c",
        ]),
        ([
                "id":          "shi bing",
                "name":        "士兵",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/bing.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "「平通鏢局」鏢頭",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/biaotou.c",
        ]),
        ([
                "id":          "lao zhangfang",
                "name":        "賬房老夫子",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/chengdu/npc/zhangfang.c",
        ]),
        ([
                "id":          "xiao zei",
                "name":        "小賊",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/chengdu/npc/xiaozei.c",
        ]),
        ([
                "id":          "cui yingying",
                "name":        "崔鶯鶯",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/city/npc/yingying.c",
        ]),
        ([
                "id":          "ya yi",
                "name":        "衙役",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/city/npc/yayi.c",
        ]),
        ([
                "id":          "guan bing",
                "name":        "官兵",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/city/npc/bing.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "鏢頭",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/city/npc/biaotou.c",
        ]),
        ([
                "id":          "xi zi",
                "name":        "戲子",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/changan/npc/xizi.c",
        ]),
        ([
                "id":          "lao zhang",
                "name":        "老張",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/changan/npc/laozhang.c",
        ]),
        ([
                "id":          "shuoshu laoren",
                "name":        "說書老人",
                "type":        "殺",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/changan/npc/laoren.c",
        ]),
        ([
                "id":          "huo ji",
                "name":        "小夥計",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/changan/npc/huoji.c",
        ]),
        ([
                "id":          "guan jia",
                "name":        "管家",
                "type":        "殺",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/changan/npc/guanjia.c",
        ]),
        ([
                "id":          "guan bing",
                "name":        "官兵",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/changan/npc/guanbing.c",
        ]),
        ([
                "id":          "flower girl",
                "name":        "賣花姑娘",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/beijing/npc/flowerg.c",
        ]),
        ([
                "id":          "zhixiang daozhang",
                "name":        "制香道長",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/wudang/zhixiang.c",
        ]),
        ([
                "id":          "zhike daozhang",
                "name":        "知客道長",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/wudang/zhike.c",
        ]),
        ([
                "id":          "shouyuan daozhang",
                "name":        "守園道長",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/wudang/shouyuan.c",
        ]),
        ([
                "id":          "qing feng",
                "name":        "清風",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/wudang/qingfeng.c",
        ]),
        ([
                "id":          "ming yue",
                "name":        "明月",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/wudang/mingyue.c",
        ]),
        ([
                "id":          "famu daozhang",
                "name":        "伐木道長",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/wudang/famu.c",
        ]),
        ([
                "id":          "xu ming",
                "name":        "虛明",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xu-ming.c",
        ]),
        ([
                "id":          "xingzhe",
                "name":        "行者",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xingzhe.c",
        ]),
        ([
                "id":          "tuobo seng",
                "name":        "託缽僧",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/tuoboseng.c",
        ]),
        ([
                "id":          "qingyuan biqiu",
                "name":        "清緣比丘",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-yuan.c",
        ]),
        ([
                "id":          "qingxiao biqiu",
                "name":        "清曉比丘",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-xiao.c",
        ]),
        ([
                "id":          "qingwu biqiu",
                "name":        "清無比丘",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wu.c",
        ]),
        ([
                "id":          "qingwen biqiu",
                "name":        "清聞比丘",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wen.c",
        ]),
        ([
                "id":          "qingwei biqiu",
                "name":        "清為比丘",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wei.c",
        ]),
        ([
                "id":          "qingshan biqiu",
                "name":        "清善比丘",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-shan.c",
        ]),
        ([
                "id":          "qingle biqiu",
                "name":        "清樂比丘",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-le.c",
        ]),
        ([
                "id":          "qingguan biqiu",
                "name":        "清觀比丘",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-guan.c",
        ]),
        ([
                "id":          "qingfa biqiu",
                "name":        "清法比丘",
                "type":        "殺",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-fa.c",
        ]),
        ([
                "id":          "daozheng chanshi",
                "name":        "道正禪師",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-zheng.c",
        ]),
        ([
                "id":          "daoyi chanshi",
                "name":        "道一禪師",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-yi.c",
        ]),
        ([
                "id":          "daoxiang chanshi",
                "name":        "道象禪師",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-xiang2.c",
        ]),
        ([
                "id":          "daoxiang chanshi",
                "name":        "道相禪師",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-xiang.c",
        ]),
        ([
                "id":          "daopin chanshi",
                "name":        "道品禪師",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-pin.c",
        ]),
        ([
                "id":          "daojue chanshi",
                "name":        "道覺禪師",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-jue.c",
        ]),
        ([
                "id":          "daoguo chanshi",
                "name":        "道果禪師",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-guo.c",
        ]),
        ([
                "id":          "daocheng chanshi",
                "name":        "道成禪師",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-cheng.c",
        ]),
        ([
                "id":          "daochen chanshi",
                "name":        "道塵禪師",
                "type":        "殺",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-chen.c",
        ]),
        ([
                "id":          "qiu wanjia",
                "name":        "裘萬家",
                "type":        "殺",
                "bonus":       73,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/qiu-wanjia.c",
        ]),
});
mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
