// Created by Smallfish For HUAXIA@2004    2004/04/24

#include <ansi.h>

mapping cloth_obj = ([
        "/d/yanziwu/obj/cloth":1,                     //暫時無處獲取
        "/d/yanziwu/npc/obj/pink_cloth":28,           //阿朱
        "/d/yanziwu/npc/obj/green_cloth":28,          //阿碧
        "/d/yanziwu/npc/obj/cloth":1,                 //暫時無處獲取
        "/d/xueshan/obj/y-jiasha":8,                  //很多
        "/d/xueshan/obj/r-jiasha":28,                 //鳩摩智
        "/d/xueshan/obj/p-jiasha":28,                 //金輪法王
        "/d/xueshan/obj/lamajiasha":12,               //祭祀喇嘛、值日喇嘛、達爾巴
        "/d/xueshan/obj/c-jiasha":20,                 //老年僧人、貢唐倉國師、靈智上人
        "/d/xueshan/obj/b-jiasha":12,                 //守寺僧兵、葛倫布、本參、本觀、本相、本因
        "/d/xuedao/obj/dachang":23,                   //血刀門山洞
        "/d/xingxiu/obj/yellow-cloth":24,             //阿紫、遊坦之
        "/d/xingxiu/obj/junfu":1,                     //暫時無處獲取
        "/d/xingxiu/obj/changpao":1,                  //暫時無處獲取
        "/d/xiaoyao/npc/obj/cloth":20,                //逍遙蒙面人、王語嫣
        "/d/xiakedao/obj/cloth":1,                    //暫時無處獲取
        "/d/xiakedao/npc/obj/ycloth":1,               //暫時無處獲取
        "/d/xiakedao/npc/obj/bcloth":1,               //暫時無處獲取
        "/d/wudang/obj/wuxingfu":15,                  //五行弟子
        "/d/wudang/obj/whiterobe":12,                 //武當比較多
        "/d/wudang/obj/greyrobe":10,                  //相當多
        "/d/wudang/obj/greenrobe":15,                 //小翠、谷虛道長、知客道長、李莫愁
        "/d/wudang/obj/bluecloth":10,                 //比較多
        "/d/wudang/obj/baguafu":15,                   //八卦弟子
        "/d/wanjiegu/npc/obj/zi-dress":1,             //暫時無處獲取
        "/d/wanjiegu/npc/obj/yan-dress":1,            //暫時無處獲取
        "/d/wanjiegu/npc/obj/xiu-cloth":1,            //暫時無處獲取
        "/d/wanjiegu/npc/obj/xian-cloth":1,           //暫時無處獲取
        "/d/wanjiegu/npc/obj/sha-dress":1,            //暫時無處獲取
        "/d/wanjiegu/npc/obj/red-dress":1,            //暫時無處獲取
        "/d/wanjiegu/npc/obj/qing-cloth":28,          //段延慶
        "/d/wanjiegu/npc/obj/qi-dress":28,            //東方不敗
        "/d/wanjiegu/npc/obj/pink-dress":28,          //木婉清
        "/d/wanjiegu/npc/obj/pink-cloth":26,          //甘寶寶
        "/d/wanjiegu/npc/obj/moon-dress":26,          //鍾靈
        "/d/wanjiegu/npc/obj/mini-dress":26,          //進喜兒
        "/d/wanjiegu/npc/obj/marry-dress":1,          //暫時無處獲取
        "/d/wanjiegu/npc/obj/liu-dress":1,            //暫時無處獲取
        "/d/wanjiegu/npc/obj/gui-dress":1,            //暫時無處獲取
        "/d/wanjiegu/npc/obj/fu-cloth":1,             //暫時無處獲取
        "/d/wanjiegu/npc/obj/feature":1,              //暫時無處獲取
        "/d/wanjiegu/npc/obj/dress":1,                //暫時無處獲取
        "/d/wanjiegu/npc/obj/color-dress":1,          //暫時無處獲取
        "/d/wanjiegu/npc/obj/cloth":22,               //來福兒、黃眉大師、鍾萬仇
        "/d/wanjiegu/npc/obj/blake-cloth":24,         //萬劫谷山路江湖豪客
        "/d/village/npc/obj/cloth":4,                 //很多
        "/d/tulong/yitian/npc/obj/jiaofu":1,          //暫時無處獲取
        "/d/tulong/tulong/npc/obj/jiaofu":22,         //明教三使
        "/d/taohua/obj/cubupao":1,                    //暫時無處獲取
        "/d/taohua/obj/bupao":28,                     //黃藥師
        "/d/taohua/obj/baiyi":26,                     //程英
        "/d/taohua/obj/baipao":22,                    //桃花島僕人
        "/d/taohua/obj/baichou":1,                    //暫時無處獲取
        "/d/suzhou/npc/obj/yunxiu":4,                 //媒婆
        "/d/suzhou/npc/obj/yayifu":15,                //蘇州衙役
        "/d/suzhou/npc/obj/longpao":0,                //不收
        "/d/shaolin/obj/xuan-cloth":12,               //少林比較多
        "/d/shaolin/obj/xu-cloth":1,                  //暫時無處獲取
        "/d/shaolin/obj/test":1,                      //暫時無處獲取
        "/d/shaolin/obj/qing-cloth":12,               //少林比較多
        "/d/shaolin/obj/hui-cloth":12,                //少林比較多
        "/d/shaolin/obj/dao-cloth":12,                //少林比較多
        "/d/shaolin/obj/cloth":10,                    //少林相當多
        "/d/shaolin/obj/cheng-cloth":8,               //少林很多
        "/d/shaolin/obj/beixin":12,                   //道相禪師索取
        "/d/quanzhou/pig/obj/rover":1,                //暫時無處獲取
        "/d/quanzhou/obj/pink_cloth":4,               //陳阿婆購買
        "/d/quanzhou/obj/cloth":1,                    //暫時無處獲取
        "/d/quanzhou/npc/obj/cloth":12,               //泉州男孩女孩
        "/d/quanzhen/npc/obj/junfu":15,               //武功鎮官兵
        "/d/quanzhen/npc/obj/jinduan":26,             //侯員外
        "/d/quanzhen/npc/obj/greyrobe":1,             //暫時無處獲取
        "/d/quanzhen/npc/obj/greenrobe":26,           //王重陽、周伯通
        "/d/quanzhen/npc/obj/grayrobe":4,             //很多
        "/d/quanzhen/npc/obj/goupi":15,               //富家側門
        "/d/quanzhen/npc/obj/cloth":4,                //很多
        "/d/mingjiao/obj/beixin":1,                   //暫時無處獲取
        "/d/mingjiao/obj/baipao":8,                   //明教很多
        "/d/meizhuang/npc/obj/qingyi":12,             //梅莊家丁
        "/d/meizhuang/npc/obj/heiyi":1,               //暫時無處獲取
        "/d/lingjiu/obj/qingyi":12,                   //靈鷲相當多
        "/d/lingjiu/obj/doupeng":12,                  //靈鷲相當多
        "/d/lingjiu/obj/changpao":28,                 //虛竹
        "/d/huanghe/npc/obj/shuikao":1,               //暫時無處獲取
        "/d/huanghe/npc/obj/changpao":28,             //樑子翁
        "/d/henshan/npc/obj/luo_cloth":28,            //劉正風
        "/d/henshan/npc/obj/blackcloth":28,           //曲洋
        "/d/heimuya/obj/cloth":1,                     //暫時無處獲取
        "/d/heimuya/npc/obj/zichoush":24,             //紫衫侍者
        "/d/heimuya/npc/obj/zaohong":28,              //楊蓮亭
        "/d/heimuya/npc/obj/hongchouxiaoshan":1,      //暫時無處獲取
        "/d/heimuya/npc/obj/cloth":4,                 //很多
        "/d/hangzhou/npc/obj/sahua-qun":26,           //情兒
        "/d/hangzhou/npc/obj/goupi":1,                //暫時無處獲取
        "/d/hangzhou/npc/obj/cloth":8,                //杭州比較多
        "/d/hangzhou/npc/obj/baibu-qingshan":26,      //月下書生
        "/d/hangzhou/honghua/obj/huangshan":28,       //霍青桐
        "/d/gumu/npc/obj/baipao":1,                   //暫時無處獲取
        "/d/guiyun/npc/obj/red_cloth":24,             //小菊、小蘭
        "/d/guiyun/npc/obj/green_cloth":28,           //南希仁
        "/d/guanwai/npc/obj/piqiu":6,                 //皮貨商購買
        "/d/fuzhou/obj/pink_cloth":4,                 //陳阿婆購買
        "/d/fuzhou/obj/cloth":1,                      //暫時無處獲取
        "/d/fuzhou/npc/obj/cloth":8,                  //福州男孩女孩
        "/d/fuzhou/npc/obj/bluecloth":1,              //暫時無處獲取
        "/d/foshan/npc/obj/magcloth":24,              //佛山胖商人、瘦商人
        "/d/foshan/npc/obj/goupi":12,                 //佛山狼狗（四隻）
        "/d/emei/obj/ycloth":24,                      //袁紫衣、周芷若
        "/d/emei/npc/obj/cloth":28,                   //窮漢
        "/d/dali/npc/obj/xiaoao":24,                  //臺夷獵手、漁夫
        "/d/dali/npc/obj/whitecloth1":22,             //南國姑娘、宮女、木婉清
        "/d/dali/npc/obj/whitecloth":20,              //擺夷女子、宮女、南國姑娘
        "/d/dali/npc/obj/wdahui":18,                  //烏夷老祭司、獵人、農夫、烏夷商販
        "/d/dali/npc/obj/wchangqun":18,               //養花女、牧羊女、牧羊人、少女
        "/d/dali/npc/obj/tongqun":16,                 //採筍人、臺夷婦女、臺夷姑娘、祭司、臺夷農婦、族長
        "/d/dali/npc/obj/tduanqun":20,                //村婦、臺夷商販
        "/d/dali/npc/obj/qun":4,                      //薛老闆購買
        "/d/dali/npc/obj/maotan":20,                  //採筍人、砍竹人、農夫
        "/d/dali/npc/obj/kenao":4,                    //歌女、薛老闆購買
        "/d/dali/npc/obj/junfu":8,                    //很多
        "/d/dali/npc/obj/jjunfu":24,                  //錦衣衛士（兩個）
        "/d/dali/npc/obj/hupi":28,                    //傣族首領
        "/d/dali/npc/obj/guazi":4,                    //薛老闆購買
        "/d/dali/npc/obj/doupeng":1,                  //暫時無處獲取
        "/d/dali/npc/obj/cynrobe":22,                 //小道姑（兩個）、刀白鳳
        "/d/dali/npc/obj/bduanqun":16,                //臺夷商販、採桑女、紡紗女、老祭司、養蠶女
        "/d/city/obj/yayifu":1,                       //暫時無處獲取
        "/d/city/obj/pink_cloth":4,                   //胡掌櫃購買、韋春芳、採花子
        "/d/city/obj/junfu":8,                        //很多
        "/d/city/obj/goupi":1,                        //暫時無處獲取
        "/d/city/obj/cloth":4,                        //很多
        "/d/city/obj/beixin":4,                       //胡掌櫃購買
        "/d/city/npc/obj/yayifu":8,                   //揚州衙門、靈州衙門
        "/d/city/npc/obj/qunzi":1,                    //暫時無處獲取
        "/d/city/npc/obj/pink_cloth":24,              //崔鶯鶯、程玉環
        "/d/city/npc/obj/junfu":10,                   //很多
        "/d/city/npc/obj/jinsijia":12,                //楊永福購買
        "/d/city/npc/obj/goupi":12,                   //比較多
        "/d/city/npc/obj/cloth":4,                    //很多
        "/d/city/npc/obj/beixin":6,                   //楊永福購買
        "/d/city/npc/cloth/zi-dress":4,               //曾柔購買
        "/d/city/npc/cloth/yan-dress":4,              //曾柔購買
        "/d/city/npc/cloth/xiu-cloth":4,              //曾柔購買
        "/d/city/npc/cloth/xian-cloth":4,             //曾柔購買
        "/d/city/npc/cloth/sha-dress":4,              //曾柔購買
        "/d/city/npc/cloth/red-dress":4,              //曾柔購買
        "/d/city/npc/cloth/qi-dress":4,               //曾柔購買
        "/d/city/npc/cloth/pink-dress":4,             //曾柔購買
        "/d/city/npc/cloth/moon-dress":4,             //曾柔購買
        "/d/city/npc/cloth/mini-dress":4,             //曾柔購買
        "/d/city/npc/cloth/marry-dress":4,            //曾柔購買
        "/d/city/npc/cloth/liu-dress":4,              //曾柔購買
        "/d/city/npc/cloth/gui-dress":4,              //曾柔購買
        "/d/city/npc/cloth/fu-cloth":4,               //曾柔購買
        "/d/city/npc/cloth/feature":4,                //曾柔購買
        "/d/city/npc/cloth/dress":1,                  //暫時無處獲取
        "/d/city/npc/cloth/color-dress":4,            //曾柔購買
        "/d/city/npc/cloth/cloth":4,                  //曾柔購買
        "/d/changan/npc/obj/yayifu":15,               //長安衙門
        "/d/changan/npc/obj/skirt":12,                //相當多
        "/d/changan/npc/obj/sengyi":24,               //寶象寺知客僧(兩個)
        "/d/changan/npc/obj/sengpao":22,              //慧通禪師、靜明、靜玄
        "/d/changan/npc/obj/linen":4,                 //夥計、店小二
        "/d/changan/npc/obj/jinzhuang":4,             //很多
        "/d/changan/npc/obj/cloth":4,                 //很多
        "/d/changan/npc/obj/choupao":10,              //相當多
        "/d/changan/npc/obj/changpao":12,             //管家、說書老人、劉老實、香客、戲子
        "/d/changan/npc/obj/bingfu":8,                //很多
        "/d/changan/npc/obj/beixin":4,                //劉老實購買
        "/d/beijing/npc/obj/nvcloth":10,              //相當多
        "/d/beijing/npc/obj/jinvcloth":24,            //妓女（兩個）
        "/d/beijing/npc/obj/jiasha":8,                //很多
        "/d/beijing/npc/obj/hupi":26,                 //歸鍾、喜來福
        "/d/beijing/npc/obj/guanfu6":8,               //很多
        "/d/beijing/npc/obj/guanfu5":20,              //城門督察（四個）、馮錫範
        "/d/beijing/npc/obj/guanfu4":15,              //東廠官兵、西廠官兵
        "/d/beijing/npc/obj/guanfu3":24,              //驍騎營侍衛(兩個）
        "/d/beijing/npc/obj/guanfu2":22,              //多隆、張康年、趙齊賢
        "/d/beijing/npc/obj/guanfu1":15,              //御前侍衛（八個）
        "/d/beijing/npc/obj/goldcloth2":28,           //康親王
        "/d/beijing/npc/obj/goldcloth1":22,           //鰲拜、多隆、鄭克爽
        "/d/beijing/npc/obj/diaoqiu":24,              //鰲拜、韋小寶
        "/d/beijing/npc/obj/cloth6":24,               //齊元凱、麥鯨、過三拳、元廣波
        "/d/beijing/npc/obj/cloth5":28,               //歸辛樹
        "/d/beijing/npc/obj/cloth4":20,               //獨臂神尼、歸二孃、富家弟子、殷素素
        "/d/beijing/npc/obj/cloth3":1,                //暫時無處獲取
        "/d/beijing/npc/obj/cloth2":22,               //酸秀才（三個）
        "/d/beijing/npc/obj/cloth1":8,                //毒郎中、柳大洪、書生、張翠山
        "/d/beijing/npc/obj/cloth":4,                 //很多
        "/d/baituo/obj/shepi":22,                     //白駝蟒蛇
        "/d/baituo/obj/qingpao":28,                   //小青
        "/d/baituo/obj/baipao":15,                    //管家、白衣少女、田伯光、歐陽克、舞蛇人
        "/d/baituo/npc/obj/shepi":1,                  //暫時無處獲取
        "/d/baituo/npc/obj/qingpao":1,                //暫時無處獲取
        "/d/baituo/npc/obj/baipao":1,                 //暫時無處獲取
        "/clone/misc/red_cloth":1,                    //公共文件一律廉價
        "/clone/misc/pink_cloth":1,                   //公共文件一律廉價
        "/clone/misc/color_cloth":1,                  //公共文件一律廉價
        "/clone/misc/cloth":1,                        //公共文件一律廉價
        "/clone/misc/black_cloth":1,                  //公共文件一律廉價
        "/clone/misc/baipao":1,                       //公共文件一律廉價
        "/clone/cloth/yunshang":1,                    //公共文件一律廉價
        "/clone/cloth/y-jiasha":1,                    //公共文件一律廉價
        "/clone/cloth/wcloth":1,                      //公共文件一律廉價
        "/clone/cloth/seng-cloth":1,                  //公共文件一律廉價
        "/clone/cloth/qingyi":1,                      //公共文件一律廉價
        "/clone/cloth/ni-cloth":1,                    //公共文件一律廉價
        "/clone/cloth/male8-cloth":1,                 //公共文件一律廉價
        "/clone/cloth/male7-cloth":1,                 //公共文件一律廉價
        "/clone/cloth/male6-cloth":1,                 //公共文件一律廉價
        "/clone/cloth/male5-cloth":1,                 //公共文件一律廉價
        "/clone/cloth/male4-cloth":1,                 //公共文件一律廉價
        "/clone/cloth/male3-cloth":1,                 //公共文件一律廉價
        "/clone/cloth/male2-cloth":1,                 //公共文件一律廉價
        "/clone/cloth/male1-cloth":1,                 //公共文件一律廉價
        "/clone/cloth/junfu":1,                       //公共文件一律廉價
        "/clone/cloth/jinduan":1,                     //公共文件一律廉價
        "/clone/cloth/female8-cloth":1,               //公共文件一律廉價
        "/clone/cloth/female7-cloth":1,               //公共文件一律廉價
        "/clone/cloth/female6-cloth":1,               //公共文件一律廉價
        "/clone/cloth/female5-cloth":1,               //公共文件一律廉價
        "/clone/cloth/female4-cloth":1,               //公共文件一律廉價
        "/clone/cloth/female3-cloth":1,               //公共文件一律廉價
        "/clone/cloth/female2-cloth":1,               //公共文件一律廉價
        "/clone/cloth/female1-cloth":1,               //公共文件一律廉價
        "/clone/cloth/daogu-cloth":1,                 //公共文件一律廉價
        "/clone/cloth/dao-cloth":1,                   //公共文件一律廉價
        "/clone/cloth/cuttonp":1,                     //公共文件一律廉價
        "/clone/cloth/cloth":1,                       //公共文件一律廉價
        "/clone/cloth/changpao":1,                    //公共文件一律廉價
        "/clone/cloth/c-jiasha":1,                    //公共文件一律廉價
        "/clone/cloth/bupao":1,                       //公共文件一律廉價
        "/clone/cloth/baipao":1,                      //公共文件一律廉價
        "/clone/book/zhanyi":1,                       //公共文件一律廉價
        "/kungfu/class/dali/obj/magcloth":28,         //高升泰
]);

int check_value(string filename)
{
        if (undefinedp(cloth_obj[filename])) return 0;
        return cloth_obj[filename];
}
