// Create by Rcwiz for Hero May 2003
//

mapping fam_info = ([

      "武當派"    :     ([ "shen_type"     :    1,                               // 門派神類型1為正神，-1為負神
                           "master_id"     :    "zhang sanfeng",                 // 門派最高Master ID
                           "master_name"   :    "張三丰",                        // 門派最高Master name
                           "master_rank"   :    "張真人",                        // 門派最高Master rank
                           "master_file"   :    CLASS_D("wudang") + "/zhang",    // 門派最高Master所屬文件
                           "master_room"   :    "/d/wudang/xiaoyuan",            // 門派最高Master起始房間
                           "fir_room_fi"   :    "/d/wudang/toutiangate",         // 挑畔者初始聚集地
                           "fir_room_nm"   :    "頭天門",
                           "tar_room_fi"   :    "/d/wudang/xiaoyuan",            // 挑畔者奪取目標地點
                           "tar_room_nm"   :    "後山小院",
                           "guard_room_fi" :    "/d/wudang/wulaofeng",           // 門派NPC守衛地點
                           "guard_room_nm" :    "五老峰",
                           "npc_list"      :    ({ 
                                                   "yu lianzhou",                // 門派中的其他NPC參與接受挑畔
                                                   "yin litin",                  // 這些NPC均會在開始時移動到
                                                   "yu daiyan",                  // master_room 並與master組隊
                                                   "song qingshu", 
                                                   "zhang songxi",
                                                   "song yuanqiao",
                                                   "mo shenggu",
                                                }),
                           "route_list"    :    ({                               // 記錄挑畔者攻打該門派所經過的路由 
                                                   "north",                      // 每次random_move()都讀取該路由表
                                                   "north",                      // 按照這個順序一直走到終點
                                                   "northdown", 
                                                   "northdown", 
                                                   "northdown", 
                                                   "northdown", 
                                                   "northdown", 
                                                   "northup", 
                                                   "northdown", 
                                                   "northdown", 
                                                   "west", 
                                                   "west", // 武當廣場
                                                   "south",
                                                   "south",
                                                   "south",
                                                   "south",
                                                   "south",
                                                 }),
                          "skill"          :     "太極劍法和太極神功",
                          "family"         :     "武當派",
                          "spe_cmds"       :     "open door",
                        ]),

      "逍遙派"    :     ([ "shen_type"     :    1,
                           "master_id"     :    "su xinghe",
                           "master_name"   :    "蘇星河",
                           "master_rank"   :    "掌門人",
                           "master_file"   :    CLASS_D("xiaoyao") + "/suxingh",
                           "master_room"   :    "/d/xiaoyao/qingcaop",
                           "fir_room_fi"   :    "/d/xiaoyao/shulin3",
                           "fir_room_nm"   :    "逍遙派樹林",
                           "tar_room_fi"   :    "/d/xiaoyao/shishi",
                           "tar_room_nm"   :    "石室",
                           "guard_room_fi" :    "/d/xiaoyao/qingcaop",
                           "guard_room_nm" :    "青草坪",
                           "npc_list"      :    ({ 
                                                   "xue muhua",
                                                   "wu lingjun",
                                                   "shi qinglu", 
                                                   "kang guangling",
                                                   "feng asan",
                                                   "fan bailing",
                                                }),
                           "route_list"    :    ({
                                                   "east",
                                                   "south",
                                                   "west",
                                                   "west",
                                                   "enter",
                                                   "down",
                                                 }),
                          "skill"          :     "天山六陽掌和北冥神功",
                          "family"         :     "逍遙派",
                        ]),

      "峨嵋派"    :     ([ "shen_type"     :    1,
                           "master_id"     :    "miejue shitai",
                           "master_name"   :    "滅絕師太",
                           "master_rank"   :    "掌門人",
                           "master_file"   :    CLASS_D("emei") + "/miejue",
                           "master_room"   :    "/d/emei/hcahoudian",
                           "fir_room_fi"   :    "/d/emei/shierpan1",
                           "fir_room_nm"   :    "十二盤",
                           "tar_room_fi"   :    "/d/emei/hcahoudian",
                           "tar_room_nm"   :    "華藏庵後殿",
                           "guard_room_fi" :    "/d/emei/leidongping",
                           "guard_room_nm" :    "雷洞坪",
                           "npc_list"      :    ({
                                                   "bei jinyi",
                                                   "jingdao shitai",
                                                   "jinghe shitai",
                                                   "zhou zhiruo", 
                                                   "jingzhen shitai",
                                                   "jingzhao shitai",
                                                   "jingxuan shitai",
                                                   "jingxu shitai",
                                                   "jingxin shitai",
                                                   "jingxian shitai",
                                                   "jingkong shitai",
                                                   "jingjia shitai",
                                                   "jinghui shitai",
                                                   "fengling shitai",
                                                   "jingfeng shitai",
                                                   "jingxuan shitai",
                                                   "jingxuan shitai",
                                                }),
                           "route_list"    :    ({
                                                   "southwest",
                                                   "westup",
                                                   "southwest",
                                                   "westup",
                                                   "westup",
                                                   "westup",
                                                   "westup",
                                                   "westup",
                                                   "southup",
                                                   "southup",
                                                   "southup",
                                                   "southwest",
                                                   "southup",
                                                   "southeast",
                                                   "westup",
                                                   "southup", // 金頂
                                                   "southeast",
                                                   "enter",
                                                   "south",
                                                   "south",
                                                   "south",
                                                 }),
                          "skill"          :     "迴風拂柳劍和峨嵋九陽神功",
                          "family"         :     "峨嵋派",
                        ]),

      "靈鷲宮"    :     ([ "shen_type"     :    1,
                           "master_id"     :    "xuzhu zhi",
                           "master_name"   :    "虛竹子",
                           "master_rank"   :    "掌門人",
                           "master_file"   :    CLASS_D("lingjiu") + "/xuzhu",
                           "master_room"   :    "/d/lingjiu/dating",
                           "fir_room_fi"   :    "/d/lingjiu/shanjiao",
                           "fir_room_nm"   :    "縹緲峰山腳",
                           "tar_room_fi"   :    "/d/lingjiu/dating",
                           "tar_room_nm"   :    "獨尊廳",
                           "guard_room_fi" :    "/d/lingjiu/xianchou",
                           "guard_room_nm" :    "仙愁門",
                           "npc_list"      :    ({
                                                   "cheng qingshuang",
                                                   "duanmu yuan",
                                                   "fu mingyi",
                                                   "ju jian", 
                                                   "lan jian",
                                                   "li furen",
                                                   "mei jian",
                                                   "sang tugong",
                                                   "shi sao",
                                                   "zhu jian",
                                                   "zhuo bufan",
                                                   "zuo zimu",
                                                }),
                           "route_list"    :    ({
                                                   "westup",
                                                   "westup",
                                                   "northup",
                                                   "eastup",
                                                   "north",
                                                   "north",
                                                   "north",
                                                 }),
                          "skill"          :     "八荒六合唯我獨尊功和天山六陽掌",
                          "family"         :     "靈鷲宮",
                          "spe_cmds"       :     "zou tiesuo",
                        ]),

      "星宿派"    :     ([ "shen_type"     :    -1,
                           "master_id"     :    "ding chunqiu",
                           "master_name"   :    "丁春秋",
                           "master_rank"   :    "老仙",
                           "master_file"   :    CLASS_D("xingxiu") + "/ding",
                           "master_room"   :    "/d/xingxiu/riyuedong",
                           "fir_room_fi"   :    "/d/xingxiu/shanjiao",
                           "fir_room_nm"   :    "天山腳下",
                           "tar_room_fi"   :    "/d/xingxiu/riyuedong",
                           "tar_room_nm"   :    "日月洞",
                           "guard_room_fi" :    "/d/xingxiu/xxh1",
                           "guard_room_nm" :    "星宿海",
                           "npc_list"      :    ({
                                                   "chuchen zi",
                                                   "tianlang zi",
                                                   "zhaixing zi",
                                                }),
                           "route_list"    :    ({
                                                   "westup",
                                                   "north",
                                                   "northdown",
                                                   "north",
                                                   "north",
                                                 }),
                          "skill"          :     "抽髓掌和毒技",
                          "family"         :     "星宿派",
                        ]),
      "全真派"    :     ([ "shen_type"     :    1,
                           "master_id"     :    "wang chongyang",
                           "master_name"   :    "王重陽",
                           "master_rank"   :    "掌門人",
                           "master_file"   :    CLASS_D("quanzhen") + "/wang",
                           "master_room"   :    "/d/quanzhen/shandong",
                           "fir_room_fi"   :    "/d/gumu/riyueyan",
                           "fir_room_nm"   :    "日月岩",
                           "tar_room_fi"   :    "/d/quanzhen/shandong",
                           "tar_room_nm"   :    "後山山洞",
                           "guard_room_fi" :    "/d/gumu/daxiaochang",
                           "guard_room_nm" :    "大校場",
                           "npc_list"      :    ({
                                                   "hao datong",
                                                   "liu chuxuan",
                                                   "ma yu",
                                                   "qiu chuji",
                                                   "tan chuduan",
                                                   "wang chuyi",
                                                   "yin zhiping",
                                                   "zhao zhijing",
                                                   "zhou botong",
                                                }),
                           "route_list"    :    ({
                                                   "northup",
                                                   "northup",
                                                   "north",
                                                   "west",
                                                   "northwest",
                                                   "north",
                                                   "northup",
                                                   "northup",
                                                   "northup",
                                                   "northup",
                                                   "northup",
                                                   "southeast",
                                                   "eastup",
                                                   "southup",
                                                   "east", // jiaobei
                                                   "eastup", // 有門
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east", // 後山 - /d/quanzhen/houshan
                                                   "northeast",
                                                   "northeast",
                                                   "east",
                                                   "enter",
                                                 }),
                          "skill"          :     "全真劍法和先天功",
                          "family"         :     "全真教",
                          "spe_cmds"       :     "open door",
                        ]),
]);