#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "mi weiyi",
                "name":        "米為義",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/henshan/mi.c",
        ]),
        ([
                "id":          "qin juan",
                "name":        "秦絹",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hengshan/npc/qin.c",
        ]),
        ([
                "id":          "yi lin",
                "name":        "儀琳",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/lin.c",
        ]),
        ([
                "id":          "yi wen",
                "name":        "儀文",
                "type":        "殺",
                "bonus":       97,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/wen.c",
        ]),
        ([
                "id":          "shi shuangying",
                "name":        "石雙英",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/shi.c",
        ]),
        ([
                "id":          "xu tianhong",
                "name":        "徐天宏",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/xu.c",
        ]),
        ([
                "id":          "wei chunhua",
                "name":        "衛春華",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/wei.c",
        ]),
        ([
                "id":          "zhu cong",
                "name":        "朱聰",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/guiyun/npc/zhucong.c",
        ]),
        ([
                "id":          "nan xiren",
                "name":        "南希仁",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guiyun/npc/nanxiren.c",
        ]),
        ([
                "id":          "ke zhene",
                "name":        "柯鎮惡",
                "type":        "殺",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/guiyun/npc/kezhene.c",
        ]),
        ([
                "id":          "han baoju",
                "name":        "韓寶駒",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guiyun/npc/hanbaoju.c",
        ]),
        ([
                "id":          "xiao yuanshan",
                "name":        "蕭遠山",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiaoyuanshan.c",
        ]),
        ([
                "id":          "yang chengxie",
                "name":        "楊成協",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/yang.c",
        ]),
        ([
                "id":          "zhang asheng",
                "name":        "張阿生",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/guiyun/npc/zhangasheng.c",
        ]),
        ([
                "id":          "han xiaoyin",
                "name":        "韓小瑩",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/guiyun/npc/hanxiaoying.c",
        ]),
        ([
                "id":          "danqing sheng",
                "name":        "丹青生",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/meizhuang/danqing.c",
        ]),
        ([
                "id":          "zheng e",
                "name":        "鄭萼",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hengshan/npc/zheng.c",
        ]),
        ([
                "id":          "li yuanzhi",
                "name":        "李沅芷",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/npc/liyuanzhi.c",
        ]),
        ([
                "id":          "hu qingyu",
                "name":        "胡慶餘",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/npc/huqingyu.c",
        ]),
        ([
                "id":          "ye erniang",
                "name":        "葉二孃",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/lingzhou/npc/ye.c",
        ]),
        ([
                "id":          "xiang danian",
                "name":        "向大年",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/henshan/xiang.c",
        ]),
        ([
                "id":          "qu yang",
                "name":        "曲洋",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/riyue/qu.c",
        ]),
        ([
                "id":          "huang boliu",
                "name":        "黃伯流",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/heimuya/npc/huangboliu.c",
        ]),
        ([
                "id":          "quan jinfa",
                "name":        "全金髮",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/guiyun/npc/quanjinfa.c",
        ]),
        ([
                "id":          "shi lingwei",
                "name":        "施令威",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/meizhuang/npc/shi.c",
        ]),
        ([
                "id":          "hu yuan",
                "name":        "護院",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/meizhuang/npc/huyuan.c",
        ]),
        ([
                "id":          "nanhai eshen",
                "name":        "南海鱷神",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/lingzhou/npc/nan.c",
        ]),
        ([
                "id":          "yu popo",
                "name":        "餘婆婆",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/yupopo.c",
        ]),
        ([
                "id":          "ren yingying",
                "name":        "任盈盈",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/huashan/npc/ren-yingying.c",
        ]),
        ([
                "id":          "chen zhiyi",
                "name":        "陳志益",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/chen.c",
        ]),
        ([
                "id":          "cheng lingsu",
                "name":        "程靈素",
                "type":        "殺",
                "bonus":       97,
                "msg":        "",
                "object":      "/kungfu/class/hu/cheng.c",
        ]),
        ([
                "id":          "mu wanqing",
                "name":        "木婉清",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/dali/npc/muwanqing.c",
        ]),
        ([
                "id":          "xiao fei",
                "name":        "蕭飛",
                "type":        "殺",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/xiaofei.c",
        ]),
        ([
                "id":          "ma wude",
                "name":        "馬五德",
                "type":        "殺",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/mawude.c",
        ]),
        ([
                "id":          "long quan",
                "name":        "龍銓",
                "type":        "殺",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/longquan.c",
        ]),
        ([
                "id":          "liu hongying",
                "name":        "劉虹瑛",
                "type":        "殺",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/liuhongying.c",
        ]),
        ([
                "id":          "chen hu",
                "name":        "陳滸",
                "type":        "殺",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/chenhu.c",
        ]),
        ([
                "id":          "shi qingshan",
                "name":        "史青山",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/city/npc/shi.c",
        ]),
        ([
                "id":          "chen youde",
                "name":        "陳有德",
                "type":        "殺",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/city/npc/chen.c",
        ]),
        ([
                "id":          "xiao yuanwai",
                "name":        "蕭員外",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/yuanwai.c",
        ]),
        ([
                "id":          "xiangxiang",
                "name":        "湘湘",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/xiangxiang.c",
        ]),
        ([
                "id":          "xiao qun",
                "name":        "蕭群",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/tongling2.c",
        ]),
        ([
                "id":          "zhang heng",
                "name":        "張衡",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/tongling1.c",
        ]),
        ([
                "id":          "huitong chanshi",
                "name":        "慧通禪師",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/huitong.c",
        ]),
        ([
                "id":          "dubi shenni",
                "name":        "獨臂神尼",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/beijing/npc/dubi.c",
        ]),
        ([
                "id":          "ma chaoxing",
                "name":        "馬超興",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/yunlong/ma.c",
        ]),
        ([
                "id":          "kang guangling",
                "name":        "康廣陵",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/kanggl.c",
        ]),
        ([
                "id":          "song qingshu",
                "name":        "宋青書",
                "type":        "殺",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/wudang/xiaosong.c",
        ]),
        ([
                "id":          "huang rong",
                "name":        "黃蓉",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/taohua/rong.c",
        ]),
        ([
                "id":          "yin zhiping",
                "name":        "尹志平",
                "type":        "殺",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/yin.c",
        ]),
        ([
                "id":          "zuo quan",
                "name":        "左全",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/zuo-qu.c",
        ]),
        ([
                "id":          "ma juwei",
                "name":        "馬俱為",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/ma-jw.c",
        ]),
        ([
                "id":          "li futou",
                "name":        "李斧頭",
                "type":        "殺",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/li-futou.c",
        ]),
        ([
                "id":          "he bujing",
                "name":        "何不淨",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/he-bj.c",
        ]),
        ([
                "id":          "jingkong shitai",
                "name":        "靜空師太",
                "type":        "殺",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/emei/kong.c",
        ]),
        ([
                "id":          "jingjia shitai",
                "name":        "靜迦師太",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/kungfu/class/emei/jia.c",
        ]),
        ([
                "id":          "ji xiaofu",
                "name":        "紀曉芙",
                "type":        "殺",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/emei/ji.c",
        ]),
        ([
                "id":          "jinghui shitai",
                "name":        "靜慧師太",
                "type":        "殺",
                "bonus":       93,
                "msg":        "",
                "object":      "/kungfu/class/emei/hui.c",
        ]),
        ([
                "id":          "jinghe shitai",
                "name":        "靜和師太",
                "type":        "殺",
                "bonus":       62,
                "msg":        "",
                "object":      "/kungfu/class/emei/he.c",
        ]),
        ([
                "id":          "jingfeng shitai",
                "name":        "靜風師太",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/emei/feng.c",
        ]),
        ([
                "id":          "jingdao shitai",
                "name":        "靜道師太",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/dao.c",
        ]),
        ([
                "id":          "bei jinyi",
                "name":        "貝錦儀",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/emei/bei.c",
        ]),
        ([
                "id":          "zhu wanli",
                "name":        "褚萬里",
                "type":        "殺",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/dali/chuwanli.c",
        ]),
        ([
                "id":          "zhu danchen",
                "name":        "朱丹臣",
                "type":        "殺",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/dali/zhudanchen.c",
        ]),
        ([
                "id":          "gu ducheng",
                "name":        "古篤誠",
                "type":        "殺",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/dali/guducheng.c",
        ]),
        ([
                "id":          "fu sigui",
                "name":        "傅思歸",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/dali/fusigui.c",
        ]),
        ([
                "id":          "chu wanli",
                "name":        "褚萬里",
                "type":        "殺",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/dali/chuwanli.c",
        ]),
});
mapping query_questkh()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
