#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "wo kou",
                "name":        "倭寇",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/taiwan/npc/wokou.c",
        ]),
        ([
                "id":          "wang furen",
                "name":        "王夫人",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/fuzhou/npc/wang.c",
        ]),
        ([
                "id":          "pu ren",
                "name":        "僕人",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/emei/npc/puren.c",
        ]),
        ([
                "id":          "zu zhang",
                "name":        "族長",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/zuzhang.c",
        ]),
        ([
                "id":          "zhao min",
                "name":        "趙敏",
                "type":        "殺",
                "bonus":       83,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhaomin2.c",
        ]),
        ([
                "id":          "zhao min",
                "name":        "趙敏",
                "type":        "殺",
                "bonus":       86,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhao.c",
        ]),
        ([
                "id":          "jiang baisheng",
                "name":        "江百勝",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taishan/npc/jiang.c",
        ]),
        ([
                "id":          "lao fuzi",
                "name":        "老夫子",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/suzhou/npc/jiaoxi.c",
        ]),
        ([
                "id":          "yafu",
                "name":        "啞婦",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hengshan/npc/yafu.c",
        ]),
        ([
                "id":          "shi tong",
                "name":        "侍童",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taohua/npc/shitong.c",
        ]),
        ([
                "id":          "tianbai daoren",
                "name":        "天柏道人",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/taishan/tianbai.c",
        ]),
        ([
                "id":          "meng jianxiong",
                "name":        "孟健雄",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/meng.c",
        ]),
        ([
                "id":          "ha dani",
                "name":        "哈達尼",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/guanwai/npc/hadani.c",
        ]),
        ([
                "id":          "lin zhennan",
                "name":        "林震南",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/fuzhou/npc/linzhennan.c",
        ]),
        ([
                "id":          "jianchu daoren",
                "name":        "建除道人",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/taishan/npc/jianchu.c",
        ]),
        ([
                "id":          "zhangli",
                "name":        "掌理道長",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/quanzhen/npc/zhangli.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "家丁",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/guiyun/npc/jiading.c",
        ]),
        ([
                "id":          "fan yifei",
                "name":        "範一飛",
                "type":        "殺",
                "bonus":       86,
                "msg":        "",
                "object":      "/d/yixing/npc/fanyifei.c",
        ]),
        ([
                "id":          "menggu bing",
                "name":        "蒙古兵",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/xiangyang/npc/menggubing.c",
        ]),
        ([
                "id":          "cheng chaofeng",
                "name":        "程嘲風",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/mingjiao/npc/chengchaofeng.c",
        ]),
        ([
                "id":          "lu dayou",
                "name":        "陸大有",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/dayou.c",
        ]),
        ([
                "id":          "zuo jiang",
                "name":        "佐將",
                "type":        "殺",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/xiangyang/npc/zuo.c",
        ]),
        ([
                "id":          "ya jiang",
                "name":        "牙將",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/xiangyang/npc/ya.c",
        ]),
        ([
                "id":          "ya pu",
                "name":        "啞僕",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taohua/npc/yapu.c",
        ]),
        ([
                "id":          "tianyi daoren",
                "name":        "天乙道人",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/taishan/tianyi.c",
        ]),
        ([
                "id":          "tiansong daoren",
                "name":        "天松道人",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/taishan/tiansong.c",
        ]),
        ([
                "id":          "zhen youqing",
                "name":        "甄有慶",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/suzhou/npc/shiye.c",
        ]),
        ([
                "id":          "an jiangang",
                "name":        "安健剛",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/an.c",
        ]),
        ([
                "id":          "jin bing",
                "name":        "大金兵",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/guiyun/npc/jinbing.c",
        ]),
        ([
                "id":          "feng liang",
                "name":        "風良",
                "type":        "殺",
                "bonus":       81,
                "msg":        "",
                "object":      "/d/yixing/npc/fengliang.c",
        ]),
        ([
                "id":          "maimaiti",
                "name":        "買賣提",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xingxiu/npc/maimaiti.c",
        ]),
        ([
                "id":          "tuo lei",
                "name":        "拖雷",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/xiangyang/npc/tuolei.c",
        ]),
        ([
                "id":          "pi jiang",
                "name":        "裨將",
                "type":        "殺",
                "bonus":       76,
                "msg":        "",
                "object":      "/d/xiangyang/npc/pi.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "青衣武士",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi3.c",
        ]),
        ([
                "id":          "yun sumei",
                "name":        "雲素梅",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/shenlong/npc/yunsumei.c",
        ]),
        ([
                "id":          "wu shi",
                "name":        "一品堂武士",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/lingzhou/npc/yipinwushi.c",
        ]),
        ([
                "id":          "wu shi",
                "name":        "石人武士",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/lingzhou/npc/shiwushi.c",
        ]),
        ([
                "id":          "yi lin",
                "name":        "儀琳",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/henshan/npc/yilin.c",
        ]),
        ([
                "id":          "feng yiming",
                "name":        "鳳一鳴",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/foshan/npc/fengyiming.c",
        ]),
        ([
                "id":          "gaoli shang",
                "name":        "高麗商",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/xiangyang/npc/gaoli.c",
        ]),
        ([
                "id":          "sun baopi",
                "name":        "孫剝皮",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/suzhou/npc/sun.c",
        ]),
        ([
                "id":          "feng zhengdong",
                "name":        "馮正東",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/suzhou/npc/feng.c",
        ]),
        ([
                "id":          "hongmao gui",
                "name":        "紅毛鬼",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/taiwan/npc/hongmao.c",
        ]),
        ([
                "id":          "zhangyao",
                "name":        "掌藥道長",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/quanzhen/npc/zhangyao.c",
        ]),
        ([
                "id":          "xiao wei",
                "name":        "校尉",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xiaowei.c",
        ]),
        ([
                "id":          "gao genming",
                "name":        "高根明",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/huashan/npc/gao-genming.c",
        ]),
        ([
                "id":          "xianghuo daoren",
                "name":        "香火道人",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/npc/xianghuo.c",
        ]),
        ([
                "id":          "zhong wanchou",
                "name":        "鍾萬仇",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/zhong.c",
        ]),
        ([
                "id":          "feng",
                "name":        "馮鐵匠",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/village/npc/smith.c",
        ]),
        ([
                "id":          "zhou yi",
                "name":        "周綺",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/zhouyi.c",
        ]),
        ([
                "id":          "lu zhengping",
                "name":        "呂正平",
                "type":        "殺",
                "bonus":       83,
                "msg":        "",
                "object":      "/d/yixing/npc/luzhengping.c",
        ]),
        ([
                "id":          "gao san",
                "name":        "高三娘子",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/yixing/npc/gaosan.c",
        ]),
        ([
                "id":          "guo fu",
                "name":        "郭芙",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/guofu.c",
        ]),
        ([
                "id":          "gan baobao",
                "name":        "甘寶寶",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/gan.c",
        ]),
        ([
                "id":          "pu ren",
                "name":        "僕人",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taohua/npc/puren.c",
        ]),
        ([
                "id":          "zhao min",
                "name":        "趙敏",
                "type":        "殺",
                "bonus":       83,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/zhaomin.c",
        ]),
        ([
                "id":          "liang fa",
                "name":        "梁發",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/liang-fa.c",
        ]),
        ([
                "id":          "lao xiucai",
                "name":        "老秀才",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/yongdeng/npc/xiucai.c",
        ]),
        ([
                "id":          "tuoba",
                "name":        "拓跋",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/mingjiao/npc/tuoba.c",
        ]),
        ([
                "id":          "gao shanwang",
                "name":        "高山王",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/mingjiao/npc/gaoshanwang.c",
        ]),
        ([
                "id":          "feng gongying",
                "name":        "封弓影",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/mingjiao/npc/fenggongying.c",
        ]),
        ([
                "id":          "shi daizi",
                "name":        "施戴子",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/shi-daizi.c",
        ]),
        ([
                "id":          "ji qingxu",
                "name":        "姬清虛",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/ji.c",
        ]),
        ([
                "id":          "xiao zhao",
                "name":        "小昭",
                "type":        "殺",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/xiaozhao.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "錦衣衛士",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/weishi2.c",
        ]),
        ([
                "id":          "daizu shouling",
                "name":        "傣族首領",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/dali/npc/shouling.c",
        ]),
        ([
                "id":          "po yi",
                "name":        "破疑",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/dali/npc/poyi.c",
        ]),
        ([
                "id":          "po chen",
                "name":        "破嗔",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/dali/npc/pochen.c",
        ]),
        ([
                "id":          "lao jisi",
                "name":        "老祭司",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/jisi1.c",
        ]),
        ([
                "id":          "ji si",
                "name":        "祭司",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/dali/npc/jisi.c",
        ]),
        ([
                "id":          "jianghu yiren",
                "name":        "江湖藝人",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/jianghuyiren.c",
        ]),
        ([
                "id":          "duan wuwei",
                "name":        "段無畏",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/duanwuwei.c",
        ]),
        ([
                "id":          "wu tiande",
                "name":        "吳天德",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/wutiande.c",
        ]),
        ([
                "id":          "tang huai",
                "name":        "唐槐",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/tanghuai.c",
        ]),
        ([
                "id":          "tang",
                "name":        "唐掌櫃",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/tanghua.c",
        ]),
        ([
                "id":          "cheng yuhuan",
                "name":        "程玉環",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/city/npc/yuhuan.c",
        ]),
        ([
                "id":          "xian laoban",
                "name":        "冼老闆",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/city/npc/xian.c",
        ]),
        ([
                "id":          "wei chunfang",
                "name":        "韋春芳",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/city/npc/wei.c",
        ]),
        ([
                "id":          "tan youji",
                "name":        "譚友紀",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/city/npc/shiye.c",
        ]),
        ([
                "id":          "mao shiba",
                "name":        "茅十八",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/city/npc/mao18.c",
        ]),
        ([
                "id":          "gui gong",
                "name":        "龜公",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/city/npc/guigong.c",
        ]),
        ([
                "id":          "cheng yaofa",
                "name":        "程藥發",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/city/npc/cheng.c",
        ]),
        ([
                "id":          "liang xinglu",
                "name":        "梁興祿",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/zhifu.c",
        ]),
        ([
                "id":          "yang laoban",
                "name":        "楊老闆",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/yang-laoban.c",
        ]),
        ([
                "id":          "li boyuan",
                "name":        "李博淵",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/xueshi.c",
        ]),
        ([
                "id":          "xiang ke",
                "name":        "香客",
                "type":        "殺",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/changan/npc/xiangke.c",
        ]),
        ([
                "id":          "tie gongji",
                "name":        "鐵公雞",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/tiegongji.c",
        ]),
        ([
                "id":          "tang",
                "name":        "趟子手",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/tang.c",
        ]),
        ([
                "id":          "shu chi",
                "name":        "書痴",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/shuchi.c",
        ]),
        ([
                "id":          "chen jisheng",
                "name":        "陳繼盛",
                "type":        "殺",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/shiye.c",
        ]),
        ([
                "id":          "monk",
                "name":        "知客和尚",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/changan/npc/monk.c",
        ]),
        ([
                "id":          "liu laoshi",
                "name":        "劉老實",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/liu.c",
        ]),
        ([
                "id":          "jin fuhuan",
                "name":        "金復還",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/jinfuhuan.c",
        ]),
        ([
                "id":          "shuang er",
                "name":        "雙兒",
                "type":        "殺",
                "bonus":       86,
                "msg":        "",
                "object":      "/d/beijing/npc/shuanger.c",
        ]),
        ([
                "id":          "qi biaoqing",
                "name":        "祁彪清",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/qibiaoqing.c",
        ]),
        ([
                "id":          "qian laoben",
                "name":        "錢老本",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/qianlaoben.c",
        ]),
        ([
                "id":          "li lishi",
                "name":        "李力世",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/beijing/npc/lilishi.c",
        ]),
        ([
                "id":          "kang qinwang",
                "name":        "康親王",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/kangqinwang.c",
        ]),
        ([
                "id":          "guan anji",
                "name":        "關安基",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/guananji.c",
        ]),
        ([
                "id":          "fan gang",
                "name":        "樊綱",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/fangang.c",
        ]),
        ([
                "id":          "feng asan",
                "name":        "馮阿三",
                "type":        "殺",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/fengas.c",
        ]),
        ([
                "id":          "qingxu daozhang",
                "name":        "清虛道長",
                "type":        "殺",
                "bonus":       96,
                "msg":        "",
                "object":      "/kungfu/class/wudang/qingxu.c",
        ]),
        ([
                "id":          "huizhen zunzhe",
                "name":        "慧真尊者",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-zhen.c",
        ]),
        ([
                "id":          "huixu zunzhe",
                "name":        "慧虛尊者",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-xu.c",
        ]),
        ([
                "id":          "huixiu zunzhe",
                "name":        "慧修尊者",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-xiu.c",
        ]),
        ([
                "id":          "huise zunzhe",
                "name":        "慧色尊者",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-se.c",
        ]),
        ([
                "id":          "huiru zunzhe",
                "name":        "慧如尊者",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-ru.c",
        ]),
        ([
                "id":          "huiming zunzhe",
                "name":        "慧名尊者",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-ming.c",
        ]),
        ([
                "id":          "huikong zunzhe",
                "name":        "慧空尊者",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-kong.c",
        ]),
        ([
                "id":          "huijie zunzhe",
                "name":        "慧潔尊者",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-jie.c",
        ]),
        ([
                "id":          "huihe zunzhe",
                "name":        "慧合尊者",
                "type":        "殺",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-he.c",
        ]),
        ([
                "id":          "mo bushou",
                "name":        "莫不收",
                "type":        "殺",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/mo-bu.c",
        ]),
        ([
                "id":          "su mengqing",
                "name":        "蘇夢清",
                "type":        "殺",
                "bonus":       96,
                "msg":        "",
                "object":      "/kungfu/class/emei/su.c",
        ]),
        ([
                "id":          "li mingxia",
                "name":        "李明霞",
                "type":        "殺",
                "bonus":       96,
                "msg":        "",
                "object":      "/kungfu/class/emei/li.c",
        ]),
        ([
                "id":          "fang bilin",
                "name":        "方碧琳",
                "type":        "殺",
                "bonus":       96,
                "msg":        "",
                "object":      "/kungfu/class/emei/fang.c",
        ]),
});
mapping query_questkh()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
string *get_questname()
{
        int i;
        string *result = ({});
        
        for (i = 0; i < sizeof(quest);i ++)
                result += ({ quest[i]["name"] });
                
        return result;
}
