inherit SKILL;
mapping *quest = ({
      (["short":                "大理北門",
       "place" :              "/d/dali/northgate",]),  
      (["short":                "揚州密林",
       "place" :              "/d/city/jiaowai5",]),  
     (["short":                "峨嵋草棚",
       "place" :              "/d/emei/caopeng",]),
     (["short":                "揚州西門",
       "place" :              "/d/city/ximen",]),
     (["short":                "雪山土路",
       "place" :              "/d/xueshan/tulu2",]),
     (["short":                "蘇州留園",
       "place" :              "/d/suzhou/liuyuan",]),
     (["short":                "蘇州寒山寺",
       "place" :              "/d/suzhou/hanshansi",]),
     (["short":                "杭州飛來峰",
       "place" :              "/d/hangzhou/feilaifeng",]),
     (["short":                "杭州淨慈寺",
       "place" :              "/d/hangzhou/jingcisi",]),
     (["short":                "杭州翠微亭",
       "place" :              "/d/hangzhou/cuiweiting",]),
     (["short":                "杭州聚景園",
       "place" :              "/d/hangzhou/jujingyuan",]),
     (["short":                "苗疆易溪部",
       "place" :              "/d/dali/yixibu",]),  
      (["short":                "揚州中央廣場",
       "place" :              "/d/city/guangchang",]),  
      (["short":                "杭州沿湖大道",
       "place" :              "/d/hangzhou/dadao1",]), 
      (["short":                "杭州斷橋",
       "place" :              "/d/hangzhou/duanqiao",]), 
      (["short":                "杭州靈隱寺",
       "place" :              "/d/hangzhou/lingyinsi",]), 
/*
      (["short":                "星宿海伊犁",
       "place" :              "/d/xingxiu/beijiang",]), 
*/
      (["short":                "武當三天門",
       "place" :              "/d/wudang/santiangate",]), 
      (["short":                "峨嵋十二盤",
       "place" :              "/d/emei/shierpan3",]), 
      (["short":                "峨嵋千佛庵",
       "place" :              "/d/emei/qianfoan",]), 
      (["short":                "峨嵋九十九道拐",
       "place" :              "/d/emei/jsjdg1",]), 
      (["short":                "明教厚土旗門",
       "place" :              "/d/mingjiao/htqmen",]), 
      (["short":                "明教烈火旗後門",
       "place" :              "/d/mingjiao/lhqhoumen",]), 
      (["short":                "福州東門",
       "place" :              "/d/fuzhou/dongmen",]), 
      (["short":                "福州北大街",
       "place" :              "/d/fuzhou/beidajie",]), 
/*
      (["short":                "星宿海沙漠",
       "place" :              "/d/xingxiu/shamo2",]),
*/
      (["short":                "少林寺石階",
       "place" :              "/d/shaolin/shijie4",]),
      (["short":                "襄陽石階",
       "place" :              "/d/xiangyang/walle1",]),
      (["short":                "華山猢猻愁",
       "place" :              "/d/huashan/husun",]),
      (["short":                "華山玉女峰",
       "place" :              "/d/huashan/yunu",]),
      (["short":                "慕容小徑",
       "place" :              "/d/mr/xiaojing1-2",]),
      (["short":                "慕容柳樹林",
       "place" :              "/d/mr/liulin",]),
      (["short":                "大理大和街",
       "place" :              "/d/dali/dahejiewest",]),
      (["short":                "蘇州城北門",
       "place" :              "/d/suzhou/beimen",]),
      (["short":                "蘇州城玄妙觀",
       "place" :              "/d/suzhou/xuanmiao",]),
      (["short":                "少林寺山門殿",
       "place" :              "/d/shaolin/smdian",]),
      (["short":                "少林寺走廊",
       "place" :              "/d/shaolin/zoulang7",]),
      (["short":                "武當山路",
       "place" :              "/d/wudang/shanlu3",]),
      (["short":                "少林寺般若堂九部",
       "place" :              "/d/shaolin/banruo9",]),
      (["short":                "雪山山腳",
       "place" :              "/d/xueshan/shanjiao",]),
      (["short":                "峨嵋九老洞",
       "place" :              "/d/emei/jiulaodong",]),
       (["short":                "峨嵋古德林",
       "place" :              "/d/emei/gudelin1",]),
       (["short":                "函古關",
       "place" :              "/d/quanzhen/hanguguan",]),
       (["short":                "終南山口",
       "place" :              "/d/quanzhen/zhongnan",]),
       (["short":                "閩江",
       "place" :              "/d/fuzhou/fzroad8",]),
       (["short":                "漢水南岸",
       "place" :              "/d/shaolin/hanshui1",]),
       (["short":                "中條山密林",
       "place" :              "/d/huashan/jzroad5",]),
       (["short":                "天山腳下",
       "place" :              "/d/xingxiu/shanjiao",]),
       (["short":                "華山腳下",
       "place" :              "/d/huashan/path1",]),
       (["short":                "平定州",
       "place" :              "/d/heimuya/pingdingzhou",]),
       (["short":                "亂石坡",
       "place" :              "/d/heimuya/road1",]),      
       ([      "short":                "華山村南村口",
                "place":                "/d/village/sexit",
        ]),([      "short":                "閩贛古道",
                "place":                "/d/fuzhou/fzroad7",
        ]),([     "short":                "玉皇頂",
                 "place":               "/d/taishan/yuhuang",
         ]),([      "short":                "六盤山",
                "place":                "/d/xingxiu/xxroad3",
        ]),([      "short":                "天山山路",
                "place":                "/d/xingxiu/tianroad1",
        ]),([      "short":                "嘉峪關",
                "place":                "/d/xingxiu/jiayuguan",
        ]),([      "short":                "西單北大街",
                "place":                "/d/city2/xidan1",
        ]),([      "short":                "武道場",
                "place":                "/d/city/wudao4",
        ]),([      "short":                "王府井大街",
                "place":                "/d/city2/wangfu2",
        ]),([      "short":                "全真教碑",
                "place":                "/d/quanzhen/jiaobei",
        ]),([      "short":                "老嫗巖",
                "place":                "/d/gumu/juyan",
        ]),([      "short":                "老龍頭",
                "place":                "/d/guanwai/laolongtou",
        ]),([      "short":                "嘉興城",
                "place":                "/d/quanzhou/jiaxing",
        ]),([      "short":                "揚州西門",
                "place":                "/d/city/ximen",
        ]),([      "short":                "仙霞嶺",
                "place":                "/d/fuzhou/fzroad1",
        ]),([      "short":                "寧遠",
                "place":                "/d/taishan/yitian",
        ]),([      "short":                "小土屋",
                "place":                "/d/guanwai/tuwu",
        ]),([      "short":                "下關城",
                "place":                "/d/dali/xiaguan",
        ]),([      "short":                "李子箐石林",
                 "place":                "/d/dali/shilin1",
        ]),([      "short":                "大疊水瀑布",
                 "place":                "/d/dali/dadieshui",
        ]),([      "short":                "羅伽甸",
                 "place":                "/d/dali/luojiadian",
        ]),([      "short":                "陽宗鎮",

                 "place":                "/d/dali/yangzong",
        ]),([      "short":                "太室闕",
                 "place":                "/d/songshan/taishique",
        ]),([      "short":                "少林石階",
                 "place":                "/d/shaolin/shijie7",
        ]),([      "short":                "鐵梁峽",
                 "place":                "/d/songshan/tieliang",
        ]),([      "short":                "峻極禪院山門",
                 "place":                "/d/songshan/junjigate",
        ]),([      "short":                "神禾原",
                 "place":                "/d/gumu/shenheyuan",
        ]),([      "short":                "終南山大校場",
                 "place":                "/d/gumu/daxiaochang",
        ]),([      "short":                "金鎖關",
                 "place":                "/d/huashan/jinsuo",
        ]),([      "short":                "平心石",
                 "place":                "/d/huashan/pingxinshi",
        ]),([      "short":                "千尺幢",
                 "place":                "/d/huashan/qianchi",
        ]),([      "short":                "山洪瀑布",
                 "place":                "/d/huashan/shanhongpb",
        ]),([      "short":                "清音閣",
                 "place":                "/d/emei/qingyinge",
        ]),([      "short":                "十二盤",
                 "place":                "/d/emei/shierpan1",
        ]),([      "short":                "九老洞口",
                 "place":                "/d/emei/jldongkou",
        ]),([      "short":                "九十九道拐",
                 "place":                "/d/emei/jsjdg2",
        ]),([      "short":                "千佛庵",
                 "place":                "/d/emei/qianfoan",
        ]),([      "short":                "終南山空地",
                 "place":                "/d/gumu/kongdi",
        ]),([      "short":                "終南山主峰",
                 "place":                "/d/gumu/zhufeng",
        ]),([      "short":                "懸天崖",
                 "place":                "/d/mingjiao/shanlu3",
        ]), ([      "short":                "烈火旗大門",
                 "place":                "/d/mingjiao/lhqmen",
        ]),([      "short":                "雪山寺山門",
                 "place":                "/d/xueshan/shanmen",
        ]),([      "short":                "洪水旗大門",
                 "place":                "/d/mingjiao/hsqmen",
        ]),([      "short":                "洪水旗大門",
                 "place":                "/d/mingjiao/hsqmen",
        ]),([      "short":                "北大街",
                 "place":                "/d/mingjiao/hsqmen",
        ]),([      "short":                "青石大道",
                 "place":                "/d/wudang/wdroad1",
        ]),([      "short":                "關洛道",
                 "place":                "/d/city4/road1",
        ]),([      "short":                "大驛道",
                 "place":                "/d/taishan/yidao",
        ]),([      "short":                "官道",
                 "place":                "/d/quanzhen/guandao2",
        ]),([      "short":                "東街",
                 "place":                "/d/quanzhen/dongjie",
        ]),([      "short":                "富家大門",
                 "place":                "/d/quanzhen/fu-damen",
        ]),([      "short":                "山路",
                 "place":                "/d/quanzhen/shanlu1",
        ]),([      "short":                "小村莊",
                 "place":                "/d/quanzhen/xiaocun",
        ]),([      "short":                "星宿海",
                 "place":                "/d/xingxiu/xxh2",
        ]),([      "short":                "天山腳下",
                 "place":                "/d/xingxiu/shanjiao",
        ]),([      "short":                "絲綢之路",
                 "place":                "/d/xingxiu/silk2",

        ]),([      "short":                "長安城西門",
                 "place":                "/d/city4/westgate",
        ]),([      "short":                "長安城東門",
                 "place":                "/d/city4/eastgate",
        ]),([      "short":                "城東門",
                 "place":                "/d/city4/eastgate",
        ]),([      "short":                "上天梯",
                 "place":                "/d/huashan/shangtianti",
        ]),([      "short":                "樹林",
                 "place":                "/d/xiaoyao/shulin3",
        ]),([      "short":                "南大街",
                 "place":                "/d/xiaoyao/shulin3",
        ]),      

   

      });

mapping query_quest()
{
  return quest[random(sizeof(quest))];
}
