//天干編號：甲、乙、丙、丁、戊、己、庚、辛、壬、癸
//地支編號：子、醜、寅、卯、辰、巳、午、未、申、酉、戌、亥
//宅基地塊細目表

mapping *house_base = ({
([
    "name"  : "皇亭街甲號",
    "place" : "無錫",
    "type"  : "user",
    "file"  : "wuxi_01",
    "value" : 5000,
]),
([
    "name"  : "皇亭街乙號",
    "place" : "無錫",
    "type"  : "user",
    "file"  : "wuxi_02",
    "value" : 5000,
]),
([
    "name"  : "皇亭街丙號",
    "place" : "無錫",
    "type"  : "user",
    "file"  : "wuxi_03",
    "value" : 4800,
]),
([
    "name"  : "皇亭街丁號",
    "place" : "無錫",
    "type"  : "user",
    "file"  : "wuxi_04",
    "value" : 4800,
]),
([
    "name"  : "皇亭街戊號",
    "place" : "無錫",
    "type"  : "user",
    "file"  : "wuxi_05",
    "value" : 5000,
]),
([
    "name"  : "皇亭街己號",
    "place" : "無錫",
    "type"  : "user",
    "file"  : "wuxi_06",
    "value" : 5000,
]),
([
    "name"  : "皇亭街庚號",
    "place" : "無錫",
    "type"  : "user",
    "file"  : "wuxi_07",
    "value" : 4800,
]),
([
    "name"  : "皇亭街辛號",
    "place" : "無錫",
    "type"  : "user",
    "file"  : "wuxi_08",
    "value" : 4800,
]),
([
    "name"  : "南山路甲號",
    "place" : "臨安",
    "type"  : "user",
    "file"  : "linan_01",
    "value" : 4000,
]),
([
    "name"  : "南山路乙號",
    "place" : "臨安",
    "type"  : "user",
    "file"  : "linan_02",
    "value" : 4000,
]),
([
    "name"  : "南山路丙號",
    "place" : "臨安",
    "type"  : "user",
    "file"  : "linan_03",
    "value" : 4000,
]),
([
    "name"  : "南山路丁號",
    "place" : "臨安",
    "type"  : "user",
    "file"  : "linan_04",
    "value" : 4000,
]),
([
    "name"  : "南山路戊號",
    "place" : "臨安",
    "type"  : "user",
    "file"  : "linan_05",
    "value" : 4000,
]),
([
    "name"  : "南山路己號",
    "place" : "臨安",
    "type"  : "user",
    "file"  : "linan_06",
    "value" : 4000,
]),
([
    "name"  : "南山路庚號",
    "place" : "臨安",
    "type"  : "user",
    "file"  : "linan_07",
    "value" : 4000,
]),
([
    "name"  : "南山路辛號",
    "place" : "臨安",
    "type"  : "user",
    "file"  : "linan_08",
    "value" : 4000,
]),
([
    "name"  : "永定街甲號",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_01",
    "value" : 4500,
]),
([
    "name"  : "永定街乙號",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_02",
    "value" : 4500,
]),
([
    "name"  : "永定街丙號",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_03",
    "value" : 4500,
]),
([
    "name"  : "永定街丁號",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_04",
    "value" : 4500,
]),
([
    "name"  : "永定街戊號",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_05",
    "value" : 4500,
]),
([
    "name"  : "永定街己號",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_06",
    "value" : 4500,
]),
([
    "name"  : "永定街庚號",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_07",
    "value" : 4500,
]),
([
    "name"  : "永定街辛號",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_08",
    "value" : 4500,
]),
([
    "name"  : "侯監集甲號",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_01",
    "value" : 3000,
]),
([
    "name"  : "侯監集乙號",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_02",
    "value" : 3000,
]),
([
    "name"  : "侯監集丙號",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_03",
    "value" : 3000,
]),
([
    "name"  : "侯監集丁號",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_04",
    "value" : 2800,
]),
([
    "name"  : "侯監集戊號",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_05",
    "value" : 2800,
]),
([
    "name"  : "侯監集己號",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_06",
    "value" : 2800,
]),
([
    "name"  : "侯監集庚號",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_07",
    "value" : 2800,
]),
([
    "name"  : "侯監集辛號",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_08",
    "value" : 2800,
]),
([
    "name"  : "鎮南街甲號",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_01",
    "value" : 3800,
]),
([
    "name"  : "鎮南街乙號",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_02",
    "value" : 3800,
]),
([
    "name"  : "鎮南街丙號",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_03",
    "value" : 3600,
]),
([
    "name"  : "鎮南街丁號",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_04",
    "value" : 3600,
]),
([
    "name"  : "鎮南街戊號",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_05",
    "value" : 3800,
]),
([
    "name"  : "鎮南街己號",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_06",
    "value" : 3800,
]),
([
    "name"  : "鎮南街庚號",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_07",
    "value" : 3600,
]),
([
    "name"  : "鎮南街辛號",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_08",
    "value" : 3600,
]),
([
    "name"  : "惠山峰腰",
    "place" : "無錫",
    "type"  : "bang",
    "file"  : "bang_01",
    "value" : 12000,
]),
([
    "name"  : "蓮蓉橋堍",
    "place" : "無錫",
    "type"  : "bang",
    "file"  : "bang_02",
    "value" : 13000,
]),
([
    "name"  : "清名橋畔",
    "place" : "無錫",
    "type"  : "bang",
    "file"  : "bang_03",
    "value" : 15000,
]),
([
    "name"  : "孤山腳下",
    "place" : "臨安",
    "type"  : "bang",
    "file"  : "bang_04",
    "value" : 10000,
]),
([
    "name"  : "清平路西",
    "place" : "福州",
    "type"  : "bang",
    "file"  : "bang_05",
    "value" : 10000,
]),
([
    "name"  : "龍泉山麓",
    "place" : "昆明",
    "type"  : "bang",
    "file"  : "bang_06",
    "value" : 9000,
]),
([
    "name"  : "西山腳下",
    "place" : "大理",
    "type"  : "bang",
    "file"  : "bang_07",
    "value" : 8000,
]),
([
    "name"  : "得勝山側",
    "place" : "揚州",
    "type"  : "bang",
    "file"  : "bang_08",
    "value" : 9000,
]),
([
    "name"  : "滄州鎮東",
    "place" : "滄州",
    "type"  : "bang",
    "file"  : "bang_09",
    "value" : 8000,
]),
([
    "name"  : "侯監林內",
    "place" : "汝州",
    "type"  : "bang",
    "file"  : "bang_10",
    "value" : 6000,
]),
([
    "name"  : "川中驛道",
    "place" : "四川",
    "type"  : "bang",
    "file"  : "bang_11",
    "value" : 7000,
]),
([
    "name"  : "北市口外",
    "place" : "北京",
    "type"  : "bang",
    "file"  : "bang_12",
    "value" : 12000,
]),
([
    "name"  : "安定門外",
    "place" : "北京",
    "type"  : "bang",
    "file"  : "bang_13",
    "value" : 10000,
]),
([
    "name"  : "燕山村西",
    "place" : "關外",
    "type"  : "bang",
    "file"  : "bang_14",
    "value" : 8000,
]),
([
    "name"  : "華山村東",
    "place" : "華山",
    "type"  : "bang",
    "file"  : "bang_15",
    "value" : 7000,
]),
([
    "name"  : "終南山腳",
    "place" : "全真",
    "type"  : "bang",
    "file"  : "bang_16",
    "value" : 6000,
]),
//---------幫會駐地二期版塊-----TOP
([
    "name"  : "太平柱石",
    "place" : "武當",
    "type"  : "bang",
    "file"  : "bang_17",
    "value" : 36000,
]),
([
    "name"  : "雙旗攬雪",
    "place" : "白駝",
    "type"  : "bang",
    "file"  : "bang_18",
    "value" : 24000,
]),
([
    "name"  : "南湖柳岸",
    "place" : "嘉興",
    "type"  : "bang",
    "file"  : "bang_19",
    "value" : 36000,
]),
([
    "name"  : "山海雄風",
    "place" : "關外",
    "type"  : "bang",
    "file"  : "bang_20",
    "value" : 26000,
]),
([
    "name"  : "大沽海景",
    "place" : "北京",
    "type"  : "bang",
    "file"  : "bang_21",
    "value" : 34000,
]),
([
    "name"  : "陽關疊韻",
    "place" : "蘭州",
    "type"  : "bang",
    "file"  : "bang_22",
    "value" : 28000,
]),
([
    "name"  : "青城尋幽",
    "place" : "青城",
    "type"  : "bang",
    "file"  : "bang_23",
    "value" : 28000,
]),
([
    "name"  : "禪鍾唱晚",
    "place" : "峨嵋",
    "type"  : "bang",
    "file"  : "bang_24",
    "value" : 30000,
]),
([
    "name"  : "玉山西風",
    "place" : "崑崙",
    "type"  : "bang",
    "file"  : "bang_25",
    "value" : 28000,
]),
([
    "name"  : "東嶽山景",
    "place" : "泰山",
    "type"  : "bang",
    "file"  : "bang_26",
    "value" : 32000,
]),
([
    "name"  : "少室問鼎",
    "place" : "少林",
    "type"  : "bang",
    "file"  : "bang_27",
    "value" : 34000,
]),
([
    "name"  : "桃花勝境",
    "place" : "峨嵋",
    "type"  : "bang",
    "file"  : "bang_28",
    "value" : 28000,
]),
//---------幫會駐地二期版塊-----END
([
    "name"  : "小蓬萊",
    "place" : "散仙莊",
    "type"  : "xian",
    "file"  : "xian_01",
    "value" : 0,
]),
([
    "name"  : "小瀛洲",
    "place" : "散仙莊",
    "type"  : "xian",
    "file"  : "xian_02",
    "value" : 0,
]),
([
    "name"  : "小方壺",
    "place" : "散仙莊",
    "type"  : "xian",
    "file"  : "xian_03",
    "value" : 0,
]),
([
    "name"  : "小員嶠",
    "place" : "散仙莊",
    "type"  : "xian",
    "file"  : "xian_04",
    "value" : 0,
]),
([
    "name"  : "小岱輿",
    "place" : "散仙莊",
    "type"  : "xian",
    "file"  : "xian_05",
    "value" : 0,
]),
});
