#include <ansi.h>

mapping all_type = ([
        "weapon" : ({ "blade", "club", "hammer", "sword", "staff", "whip", "throwing", "xsword", }),
        "armor"  : ({ "armor", "boots", "cloth", "hands", "finger", "head", "waist", "wrists", "surcoat", }),
        "rings"  : ({ "rings", "neck", "charm", }),
        "gem"    : ({ "gem", }),
]);

string *weapon_type = ({
        "blade", "hammer", "sword", "staff", "whip", "club", "throwing", "xsword",
}); 

string *armor_type = ({
        "armor", "boots", "cloth", "hands", "finger", "head", "waist", "wrists", "surcoat",
});

string *rings_type = ({
        "rings", "neck", "charm",
});

string *item_color = ({
          HIW,         HIB,         HIC,         HIR,         HIM,         HIY,         HIG,
          WHT,         BLU,         CYN,         RED,         MAG,         YEL,         NOR,
});

mapping type_list = ([
        "blade"                :        
                ([
                        "金背大砍刀"        :        "jinbei blade", 
                        "門扇大刀"        :        "menshan blade", 
                        "齊鳳朝陽刀"        :        "chaoyang blade",  
                        "象鼻古月刀"        :        "guyue blade",  
                        "砍山刀"        :        "kanshan blade",  
                        "三尖兩刃刀"        :        "sanjian blade",  
                        "合扇板門刀"        :        "heshan blade", 
                        "金背砍山刀"        :        "kanshan blade",  
                        "雁翎刀"        :        "yanling blade",  
                        "青銅刀"        :        "qingtong blade",  
                        "丹鳳刀"        :        "danfeng blade",  
                        "板門紅纓刀"        :        "hongying blade",  
                        "鏽絨刀"        :        "xiurong blade",  
                        "七星摺花刀"        :        "qixing blade",  
                        "虎牙刀"        :        "huya blade", 
                        "九耳八環刀"        :        "bahuan blade",  
                        "魚鱗紫金刀"        :        "yulin blade",  
                        "三叉鬼頭刀"        :        "guitou blade",  
                        "亮銀刀"        :        "liangyin blade",  
                        "電光刀"        :        "dianguang blade",  
                        "七寶措金刀"        :        "cuojin blade",  
                        "赤銅刀"        :        "chitong blade",  
                        "劈水刀"        :        "pishui blade",  
                        "青鋼刀"        :        "qinggang blade", 
                ]),

        "hammer"        :        
                ([
                        "八楞紫金錘"        :        "zijin hammer",   
                        "八楞黃金錘"        :        "huangjin hammer",    
                        "八卦生銅錘"        :        "shengtong hammer",    
                        "八楞亮銀錘"        :        "liangyin hammer",    
                        "鑌鐵軋油錘"        :        "bingtie hammer",    
                        "八卦亮銀錘"        :        "bagua hammer",    
                        "擂鼓甕金錘"        :        "leigu hammer",    
                        "龍頭鏈子錘"        :        "longtou hammer",   
                        "八楞生鐵錘"        :        "baleng hammer",    
                        "八卦鑌鐵錘"        :        "bagua hammer",    
                        "黑虎銅錘"        :        "heihu hammer",    
                        "烏金錘"        :        "wujin hammer",    
                        "壓把懶龍錘"        :        "lanlong hammer",    
                        "人面赤銅錘"        :        "chitong hammer",    
                        "瓜梭錘"        :        "guasuo hammer",    
                        "八寶電光錘"        :        "dianguang hammer",    
                        "青銅鏈子錘"        :        "lianzi hammer",    
                        "電光紫金錘"        :        "zijin hammer",    
                        "八稜銅錘"        :        "baleng hammer",    
                        "渾圓錘"        :        "hunyuan hammer",    
                        "青銅窩瓜錘"        :        "wogua hammer",   
                        "子母鴛鴦錘"        :        "zimu hammer",    
                        "亮銀鏈子錘"        :        "lianzi hammer",    
                        "八角紫金錘"        :        "bajiao hammer",    
                        "紅銅錘"        :        "hongtong hammer",    
                        "八寶亮銀錘"        :        "babao hammer",    
                ]),
        "sword"                :        
                ([
                        "松紋古定劍"        :        "guding sword",   
                        "七星鎏虹劍"        :        "liuhong sword",    
                        "烈焰青鋒劍"        :        "qingfeng sword",    
                        "透龍劍"        :        "toulong sword",    
                        "喪門寶劍"        :        "sanmeng sword",    
                        "紫電青霜劍"        :        "zidian sword",    
                        "紫霜劍"        :        "zishuang sword",    
                        "碧靈劍"        :        "biling sword",    
                        "盤蛇寶劍"        :        "panshe sword",    
                        "盤龍寶劍"        :        "panlong sword",    
                        "天狼劍"        :        "tianlang sword",    
                        "烏鉤劍"        :        "wugou sword",    
                        "青鋼劍"        :        "qinggang sword",    
                        "鴛鴦劍"        :        "yanyang sword",    
                        "青萍劍"        :        "qingping sword",    
                        "太合劍"        :        "taihe sword",    
                        "日月火龍劍"        :        "huolong sword",    
                        "青龍劍"        :        "qinglong sword",    
                        "誅龍劍"        :        "zhulong sword",    
                        "困龍劍"        :        "kunlong sword",    
                        "寒光劍"        :        "hanguang sword",    
                        "柳葉劍"        :        "liuye sword",    
                        "分天劍"        :        "fentian sword",    
                        "落葉青鋒劍"        :        "luoye sword",   
                        "二刃青鋼劍"        :        "qinggang sword",    
                        "長虹劍"        :        "changhong sword",   
                        "斬仙劍"        :        "zhanxian sword",    
                        "烏龍劍"        :        "wulong sword",    
                        "青雲劍"        :        "qingyun sword",    
                        "梨花寶劍"        :        "lihua sword",    
                        "白光劍"        :        "baiguang sword",    
                        "裁雲寶劍"        :        "caiyun sword",    
                ]),
        "staff"                :        
                ([
                        "陰陽杖"        :        "yinyang staff",   
                        "驌瀨杖"        :        "lilai staff",  
                        "墨角杖"        :        "mojiao staff",  
                        "牛角杖"        :        "niujiao staff",  
                        "獨龍杖"        :        "dulong staff",  
                        "七星臥魚杖"        :        "woyu staff",  
                        "鑌鐵丁字杖"        :        "dingzi staff",  
                        "鑌鐵懷抱杖"        :        "huaibao staff",  
                        "龍頭杖"        :        "longtou staff",  
                        "虎頭杖"        :        "hutou staff", 
                        "七星杖"        :        "qixing staff",  
                        "護手雙鐵杖"        :        "hushou staff",  
                        "鴛鴦杖"        :        "yanyang staff",  
                        "單刀臥魚杖"        :        "woyu staff",  
                        "沉香杖"        :        "chenxiang staff",  
                        "勾摟虎頭杖"        :        "goulou staff",  
                        "鑌鐵鴛鴦杖"        :        "yanyang staff", 
                ]),
        "club"                :        
                ([
                        "水火囚龍棒"        :        "qiulong club",   
                        "開山棒"        :        "kaishan club", 
                        "釘釘狼牙棒"        :        "dingding club", 
                        "滲金蒺藜棒"        :        "shenjin club", 
                        "紫金虯龍棒"        :        "zijin club", 
                        "烏油棒"        :        "wuyou club", 
                        "八稜棒"        :        "baleng club", 
                        "龍頭軟棒"        :        "longtou club", 
                        "渾鐵棒"        :        "huntie club", 
                        "天罡棒"        :        "tiangang club", 
                        "獨龍滲金棒"        :        "dulong club", 
                        "行者棒"        :        "xingzhe club", 
                        "亮銀狼牙棒"        :        "langya club", 
                        "青銅蒺藜棒"        :        "qingtong club", 
                        "鑌鐵螺絲棒"        :        "luosi club", 
                        "金絲藤蛇棒"        :        "tengshe club", 
                        "金光狼牙棒"        :        "jinguang club", 
                        "百釘狼牙棒"        :        "baiding club", 
                        "紫藤軟棒"        :        "ziteng club", 
                        "青銅棒槌"        :        "qingtong club", 
                        "金絲棒槌"        :        "jinsi club",
                ]),
        "whip"                :        
                ([
                        "亮銀鞭"        :        "liangyin whip",
                        "竹節鋼鞭"        :        "zhujie whip",
                        "豹尾鞭"        :        "baowei whip", 
                        "打將鞭"        :        "dajiang whip", 
                        "駝骨陰風鞭"        :        "tuogu whip", 
                        "金龍鞭"        :        "jinlong whip", 
                        "虎尾鋼鞭"        :        "huwei whip", 
                        "鑌鐵鞭"        :        "bingtie whip", 
                        "龍頭鳳尾鞭"        :        "longtou whip", 
                        "虎眼鋼鞭"        :        "huyan whip", 
                        "金絲軟鞭"        :        "jinsi whip", 
                        "葫蘆鞭"        :        "hulu whip", 
                        "龜骨鞭"        :        "guigu whip", 
                        "魚尾鞭"        :        "yugu whip", 
                        "蛇骨鞭"        :        "shegu whip", 
                        "銀絲軟鞭"        :        "yinsi whip", 
                        "遮雲掃龍鞭"        :        "zheyun whip", 
                ]),

        "cloth"                :        
                ([
                        "麻布衣"        :        "mabu cloth",
                        "棉布衣"        :        "mianbu cloth",
                        "綢布衣"        :        "choubu cloth",
                        "飛雪衣"        :        "feixue cloth",
                        "夜魔衣"        :        "yemo cloth",
                        "青絲衣"        :        "qingsi cloth",
                        "九天袍"        :        "jiutian cloth",
                        "虛無袍"        :        "xuwu cloth",
                        "青冥袍"        :        "qingming cloth",
                        "雲羅衣"        :        "yunluo cloth",
                        "絲綢長袍"        :        "silk cloth",
                ]),
        "head"                :        
                ([
                        "鬧龍垂頭"        :        "naolong kui",
                        "夜明盔"        :        "yeming kui",
                        "鳳翅金盔"        :        "fengchi kui",
                        "銅荷葉盔"        :        "heye kui",
                        "黃金帥字盔"        :        "huangjin kui", 
                        "銀練盔"        :        "yinlian kui",
                        "分水盔"        :        "fenshui kui",
                        "五鳳朝陽盔"        :        "chaoyang kui", 
                        "鳳翅月明盔"        :        "fengchi kui", 
                        "狼牙盔"        :        "langya kui", 
                        "五鳳花盔"        :        "wufeng kui", 
                        "太歲盔"        :        "taisui kui", 
                        "鑽天盔"        :        "zuantian kui",
                        "亮銀虎頭盔"        :        "hutou kui", 
                        "豹子盔"        :        "baozi kui", 
                        "蝴蝶金盔"        :        "hudie kui", 
                        "雙鳳冠"        :        "shuangfeng guan", 
                        "金鳳冠"        :        "jinfeng guan",  
                        "赤金冠"        :        "chijin guan",  
                        "金霞冠"        :        "jinxia guan", 
                        "紫金冠"        :        "zijin guan",  
                        "束髮金冠"        :        "shufa guan",  
                        "九雲烈焰冠"        :        "lieyan guan", 
                ]),
        "neck"                :        
                ([
                        "黑狐頸鍊"        :        "heihu necklace",
                        "女神頸鍊"        :        "nvshen necklace",
                        "銀項鍊"        :        "yin necklace",
                        "銅項鍊"        :        "tong necklace",
                        "金項鍊"        :        "jin necklace",
                        "藍玉項鍊"        :        "lanyu necklace",
                        "黃水晶項鍊"        :        "shuijing necklace",
                        "青銅項鍊"        :        "qingtong necklace",
                        "蔥頭項鍊"        :        "congtou necklace",
                        "骷髏項鍊"        :        "kulou necklace",
                        "古樹項鍊"        :        "gushu necklace",
                        "翡翠項鍊"        :        "feicui necklace",
                        "冰鱗項鍊"        :        "binglin necklace",
                ]),
        "armor"                :
                ([
                        "柳葉綿竹鎧"        :        "liuye armor",
                        "大葉魚鱗甲"        :        "yulin armor",
                        "大葉龍鱗甲"        :        "longlin armor",
                        "鑌鐵甲"        :        "bingtie armor", 
                        "赤金鎧甲"        :        "chijin armor", 
                        "黃金甲"        :        "huangjin armor",
                        "龜背甲"        :        "guibei armor",
                        "墨魚甲"        :        "moyu armor",
                        "赤銅大葉甲"        :        "chitong armor",
                        "銀裝甲"        :        "yinzhuang armor", 
                        "連環鑌鐵鎧"        :        "lianhuan armor",
                        "月落紅雲甲"        :        "yueluo armor",
                        "金絲軟甲"        :        "jinsi armor",
                        "紫藤甲"        :        "ziteng armor",
                        "紫金護心甲"        :        "huxin armor", 
                        "荷葉連環甲"        :        "heye armor", 
                ]),
        "surcoat"        :        
                ([
                        "夜光披風"        :        "yeguang pifeng",
                        "黃金披風"        :        "huangjin pifeng",
                        "綿布斗篷"        :        "mianbu pifeng",
                        "羊皮斗篷"        :        "yangpi pifeng",
                        "綢緞斗篷"        :        "chouduan pifeng",
                        "赤紅斗篷"        :        "chihong pifeng",
                        "靈角披風"        :        "lingjiao pifeng",
                        "戰月披風"        :        "zhanyue pifeng",
                        "異獸披風"        :        "yishou pifeng",
                ]),
        "waist"                :        
                ([
                        "帆布腰帶"        :        "fanbu waist",
                        "真皮腰帶"        :        "zhenpi waist",
                        "編織腰帶"        :        "bianzhi waist",
                        "粗布腰帶"        :        "cubu waist",
                        "生鐵腰帶"        :        "shengtie waist",
                        "琥珀腰帶"        :        "hupo waist",
                        "冰鱗腰帶"        :        "binglin waist",
                        "白銀腰帶"        :        "baiying waist",
                        "翡翠腰帶"        :        "feicui waist",
                ]),
        "wrists"        :        
                ([
                        "粗布護腕"        :        "cubu wrists",
                        "紫竹護腕"        :        "zizhu wrists",
                        "古木護腕"        :        "gumu wrists",
                        "青銅護腕"        :        "qingtong wrists",
                        "精鐵護腕"        :        "jingtie wrists",
                        "翡翠護腕"        :        "feicui wrists",
                        "黃金護腕"        :        "huangjin wrists",
                        "冰鱗護腕"        :        "bingling wrists",
                ]),
        "finger"        :
                ([
                        "永恆戒指"        :        "yongheng ring",
                        "花戒指"        :        "hua ring",
                        "銀戒指"        :        "yin ring",
                        "威嚴戒指"        :        "weiyan ring",
                        "首領戒指"        :        "shouling ring",
                        "古樹戒指"        :        "gushu ring",
                        "隱士戒指"        :        "yinshi ring",
                        "十字骨戒"        :        "shizi ring",
                        "水晶戒指"        :        "shuijing ring",
                        "冰鱗戒指"        :        "bingling ring",
                        "翡翠戒指"        :        "feicui ring",
                        "飛雪戒指"        :        "feixue ring",
                        "紫竹戒指"        :        "zizhu ring",
                        "獸骨戒指"        :        "shougu ring",
                ]),
        "hands"                :        
                ([
                        "流雲手套"        :        "liuyun glove",
                        "赤煉手套"        :        "chilian glove",
                        "虛無手套"        :        "xuwu glove",
                        "鎦金手套"        :        "liujin glove",
                        "鑌鐵手套"        :        "bingtie glove",
                ]),
        "boots"                :        
                ([
                        "流雲靴"        :        "liuyun shoes",
                        "赤煉靴"        :        "chilian shoes",
                        "虛無靴"        :        "xuwu shoes",
                        "鎦金靴"        :        "liujin shoes",
                        "火龍靴"        :        "huolong shoes",
                        "獸皮靴"        :        "shoupi shoes",
                        "銅牙靴"        :        "tongya shoes",
                        "精鐵靴"        :        "jingtie shoes",
                        "乘風靴"        :        "chengfeng shoes",
                        "虎紋靴"        :        "huwen shoes",
                        "破浪靴"        :        "polang shoes",
                ]),
]);
