nosave mapping weapon_shuxing = ([
"damage"        : "物理攻擊",
"str"      : "臂力",
"int"  : "悟性",
"con"  : "根骨",
"dex"      : "身法",
"kar"         : "福緣",
"per"   : "容貌",
"dodge"         : "輕功",
"unarmed"       : "拳腳",
"force"         : "內功",
"parry"         : "招架",
"sword"         : "劍法",
"blade"         : "刀法",
"axe"           : "斧法",
"stick"         : "棒法",
"staff"         : "杖法",
"spear"         : "槍法",
"fork"          : "叉法",
"club"          : "棍法",
"throwing"      : "暗器",
"hammer"        : "錘法",
"taoism"        : "道學心法",
"whip"          : "鞭法",
"strike"        : "掌法",
"finger"        : "指法",
"magic"         : "法術",
"spells"        : "咒文",
"poison"        : "毒功",
"hand"          : "手法",
"cuff"          : "拳法",
"claw"          : "爪法"
]);

nosave mapping armor_shuxing = ([
"armor"         : "物理防禦",
"str"      : "臂力",
"int"  : "悟性",
"con"  : "根骨",
"dex"      : "身法",
"kar"         : "福緣",
"per"   : "容貌",
"dodge"         : "輕功",
"unarmed"       : "拳腳",
"force"         : "內功",
"parry"         : "招架",
"sword"         : "劍法",
"blade"         : "刀法",
"axe"           : "斧法",
"stick"         : "棒法",
"staff"         : "杖法",
"spear"         : "槍法",
"fork"          : "叉法",
"club"          : "棍法",
"throwing"      : "暗器",
"hammer"        : "錘法",
"taoism"        : "道學心法",
"whip"          : "鞭法",
"strike"        : "掌法",
"finger"        : "指法",
"magic"         : "法術",
"spells"        : "咒文",
"poison"        : "毒功",
"hand"          : "手法",
"cuff"          : "拳法",
"claw"          : "爪法",
"armor_vs_force": "真氣護體"
]);