//物品
mapping weapon_file =
([
        "sword"  : "/clone/weapon/gangjian",   //鋼劍
        "blade"  : "/clone/weapon/gangdao",    //鋼刀
        "hammer" : "/clone/weapon/falun",      //法輪
        "staff"  : "/clone/weapon/gangzhang",  //鋼杖
        "whip"   : "/clone/weapon/changbian",  //長鞭
]);

//色彩
string *all_color =
({
        "$WHT$", "$YEL$", "$MAG$", "$CYN$", "$BLU$", "$GRN$", "$RED$",
        "$HIW$", "$HIY$", "$HIM$", "$HIC$", "$HIB$", "$HIG$", "$HIR$",
});

//中綴
mapping name_a =
([
        /*
        "錯筋" : "cuojin",
        "化骨" : "huagu",
        "碎心" : "suixin",
        "損精" : "sunjing",
        "吸血" : "xixue",
        */
        "幽溟" : "youming",
        "雷鳴" : "leiming",
        "涅磐" : "niepan",
        "紫陽" : "ziyang",
        "赤陰" : "chiyin",
        "裂天" : "lietian",
        "攝魂" : "shehun",
        "摩羅" : "moluo",
        "火陽" : "huoyang",
        "繽天" : "bintian",
        "鈞天" : "juntian",
        "龍炎" : "longyan",
        "赤霞" : "chixia",
        "青虹" : "qinghong",
        "帝闕" : "dique",
        "古月" : "guyue",
        "伏魔" : "fumo",
        "離火" : "lihuo",
        "修羅" : "xiuluo",
        "星月" : "xingyue",
        "追魂" : "zhuihun",
        "混天" : "huntian",
        "混元" : "hunyuan",
        "追魂" : "zhuihun",
        "奪命" : "duoming",
//////////////////////////////
        "失神" : "shishen",
        "熾日" : "zhiri",
        "弒神" : "shishen",
        "憐星" : "lianxing",
        "無神" : "wushen",
        "邀月" : "yaoyue",
        "噬魔" : "shimo",
        "月霞" : "yuexia",
        "除魔" : "chumo",
        "神風" : "shenfeng",
        "空絕" : "kongjue",
        "月潔" : "yuejie",
        "風行" : "fengxing",
        "凌風" : "lingfeng",
        "飛花" : "feihua",
        "逐月" : "zhuyue",
        "飄星" : "piaoxing",
        "炫星" : "xuanxing",
        "蝶舞" : "diewu",
        "空寂" : "kongji",
        "飄月" : "piaoyue",
        "靈風" : "lingfeng",
        "夢神" : "mengshen",
        "斷情" : "duanqing",
        "追星" : "zhuixing",
        "靈慧" : "linghui",
        "傲雪" : "aoxue",
        "吟龍" : "yinlong",
        "殘月" : "canyue",
        "定風" : "dingfeng",
        "浩光" : "haoguang",
        "情義" : "qingyi",
        "毫光" : "haoguang",
        "靈星" : "lingxing",
        "七星" : "qixing",
        "斷月" : "duanyue",
        "追雲" : "zhuiyun",
        "豪情" : "haoqing",
        "劍心" : "jianxin",
        "凌雲" : "lingyun",
        "龍形" : "longxing",
        "斷脈" : "duanmai",
        "絕情" : "jueqing",
        "破空" : "pokong",
        "斬魔" : "zhanmo",
        "乾坤" : "qiankun",
        "鴻星" : "hongxing",
        "斷空" : "duankong",
        "掠影" : "lueying",
        "幻影" : "huanying",
        "讕星" : "lanxing",
        "滾龍" : "gunlong",
        "飄雪" : "piaoxue",
        "覆雨" : "fuyu",
        "翻雲" : "fanyun",
        "降魔" : "xiangmo",
        "秋寒" : "qiuhan",
        "電光" : "dianguang",
        "風雷" : "fenglei",
        "蔽日" : "biri",
        "幻魔" : "huanmo",
        "虛冥" : "xumi",
        "幽明" : "youming",
        "溟神" : "mingshen",
        "炎獄" : "yanyu",
        "焰心" : "yanxin",
        "風影" : "fengying",
        "偃月" : "yanyue",
        "雁行" : "yanxing",
        "龍蛇" : "longshe",
        "靈蛇" : "lingshe",
        "渺空" : "miaokong",
        "曜星" : "yaoxing",
        "望空" : "wangkong",
        "塵心" : "chenxin",
        "幻月" : "huanyue",
        "絕塵" : "juechen",
        "長恨" : "changhen",
        "馳風" : "chifeng",
        "天行" : "tianxing",
        "天罡" : "tiangang",
        "地煞" : "disha",
        "蛟龍" : "jiaolong",
        "龍神" : "longshen",
        "長空" : "changkong",
        "噬谷" : "shigu",
        "風刃" : "fengren",
        "寒光" : "hanguang",
        "定心" : "dingxin",
        "幻舞" : "huanwu",
        "翌日" : "yiri",
        "古錠" : "guding",
        "天玄" : "tianxuan",
        "太極" : "taiji",
        "天風" : "tianfeng",
        "無極" : "wuji",
////////////////////////////////
        "沉水" : "chenshui",
        "赤焰" : "chiyan",
        "蕩寇" : "dangkou",
        "彗月" : "huiyue",
        "照夜" : "zhaoye",
        "追日" : "zhuiri",
        "斷闕" : "duanque",
        "刑天" : "xingtian",
        // 機杼、蒼野、青幽、百戰、鬼烈、巨靈、深罡、九日
        // 惡來、玄狐、洛神、盤瓠、儵忽、帝江、燭陰、盤古
]);

//前綴
mapping name_b =
([
        "冰心" : "bingxin",
        "寒月" : "hanyue",
        "玄天" : "xuantian",
        "雪蟬" : "xuechan",
        "青璃" : "qingli",
        "紫焰" : "ziyan",
        "太玄" : "taixuan",
        "烈焰" : "lieyan",
        "貫日" : "guanri",
        "破月" : "poyue",
        "青龍" : "qinglong",
        "白虎" : "baihu",
        "朱雀" : "zhuque",
        "玄武" : "xuanwu",
        "盤古" : "pangu",
]);
