#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "zhenzhu",
                "name":        "大珍珠",
                "type":        "尋",
                "bonus":       85,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/zhenzhu.c",
        ]),
        ([
                "id":          "dodgebook",
                "name":        "輕功篇",
                "type":        "尋",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/yanziwu/obj/dodgebook.c",
        ]),
        ([
                "id":          "green cloth",
                "name":        "[1;32m青布衣[2;37;0m",
                "type":        "尋",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/green_cloth.c",
        ]),
        ([
                "id":          "bian dan",
                "name":        "熟鐵扁擔",
                "type":        "尋",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/biandan.c",
        ]),
        ([
                "id":          "tiepipa",
                "name":        "[1;36m鐵琵琶[2;37;0m",
                "type":        "尋",
                "bonus":       53,
                "msg1":        "",
                "object":      "/d/guanwai/npc/obj/tiepipa.c",
        ]),
        ([
                "id":          "pink cloth",
                "name":        "粉紅綢衫",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/fuzhou/obj/pink_cloth.c",
        ]),
        ([
                "id":          "pangguan bi",
                "name":        "[1;36m判官筆[2;37;0m",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/bi.c",
        ]),
        ([
                "id":          "da dao",
                "name":        "大刀",
                "type":        "尋",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/dadao.c",
        ]),
        ([
                "id":          "card1",
                "name":        "風雷堂令牌",
                "type":        "尋",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/card1.c",
        ]),
        ([
                "id":          "jian dao",
                "name":        "尖刀",
                "type":        "尋",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/jiandao.c",
        ]),
        ([
                "id":          "tongren",
                "name":        "[1;33m獨腳銅人[2;37;0m",
                "type":        "尋",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/guanwai/npc/obj/tongren.c",
        ]),
        ([
                "id":          "fuchen",
                "name":        "拂塵",
                "type":        "尋",
                "bonus":       92,
                "msg1":        "",
                "object":      "/d/quanzhou/obj/fuchen.c",
        ]),
        ([
                "id":          "gebu changpao",
                "name":        "葛布長袍",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/changpao.c",
        ]),
        ([
                "id":          "changjian",
                "name":        "長劍",
                "type":        "尋",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/changjian.c",
        ]),
        ([
                "id":          "zhe shan",
                "name":        "油紙摺扇",
                "type":        "尋",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/zheshan.c",
        ]),
        ([
                "id":          "gan cheng",
                "name":        "桿秤",
                "type":        "尋",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/gancheng.c",
        ]),
        ([
                "id":          "fu",
                "name":        "砍柴斧",
                "type":        "尋",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/axe.c",
        ]),
        ([
                "id":          "tie zhang",
                "name":        "[37m精鐵杖[2;37;0m",
                "type":        "尋",
                "bonus":       81,
                "msg1":        "",
                "object":      "/d/tulong/yitian/npc/obj/tiezhang.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "黑色布衣",
                "type":        "尋",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/henshan/npc/obj/blackcloth.c",
        ]),
        ([
                "id":          "zijin chui",
                "name":        "紫金錘",
                "type":        "尋",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/zijinchui.c",
        ]),
        ([
                "id":          "zhangfa tu2",
                "name":        "天山六陽掌法圖下冊",
                "type":        "尋",
                "bonus":       85,
                "msg1":        "",
                "object":      "/clone/book/liuyang_book2.c",
        ]),
        ([
                "id":          "zhangfa tu1",
                "name":        "天山六陽掌法圖上冊",
                "type":        "尋",
                "bonus":       85,
                "msg1":        "",
                "object":      "/clone/book/liuyang_book1.c",
        ]),
        ([
                "id":          "gangzhang",
                "name":        "鋼杖",
                "type":        "尋",
                "bonus":       85,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/gangzhang.c",
        ]),
        ([
                "id":          "changbian",
                "name":        "鐵鞭",
                "type":        "尋",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/hangzhou/honghua/obj/tiebian.c",
        ]),
        ([
                "id":          "jiasha",
                "name":        "[1;33m黃色袈裟[2;37;0m",
                "type":        "尋",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/xueshan/obj/y-jiasha.c",
        ]),
        ([
                "id":          "seng mao",
                "name":        "[1;31m僧帽[2;37;0m",
                "type":        "尋",
                "bonus":       70,
                "msg1":        "",
                "object":      "/d/xueshan/obj/sengmao.c",
        ]),
        ([
                "id":          "tong bo",
                "name":        "[33m銅鈸[2;37;0m",
                "type":        "尋",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/tulong/yitian/npc/obj/tongbo.c",
        ]),
        ([
                "id":          "ruanwei jia",
                "name":        "軟蝟甲",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/taohua/obj/ruanwei.c",
        ]),
        ([
                "id":          "pao",
                "name":        "[37m灰色道袍[2;37;0m",
                "type":        "尋",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/quanzhen/npc/obj/grayrobe.c",
        ]),
        ([
                "id":          "shan",
                "name":        "青布長衫",
                "type":        "尋",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/wudang/obj/bluecloth.c",
        ]),
        ([
                "id":          "pao",
                "name":        "青色道袍",
                "type":        "尋",
                "bonus":       92,
                "msg1":        "",
                "object":      "/d/wudang/obj/greenrobe.c",
        ]),
        ([
                "id":          "jindai",
                "name":        "束髮金帶",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/taohua/obj/shudai.c",
        ]),
        ([
                "id":          "pi beixin",
                "name":        "皮背心",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/city/obj/beixin.c",
        ]),
        ([
                "id":          "armor",
                "name":        "鐵甲",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/city/npc/obj/tiejia.c",
        ]),
        ([
                "id":          "zhan armor",
                "name":        "戰甲",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/zhanjia.c",
        ]),
        ([
                "id":          "skirt",
                "name":        "輕紗長裙",
                "type":        "尋",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/skirt.c",
        ]),
        ([
                "id":          "seng pao",
                "name":        "[1;33m僧袍[2;37;0m",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/sengpao.c",
        ]),
        ([
                "id":          "hammer",
                "name":        "鐵錘",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/hammer.c",
        ]),
        ([
                "id":          "changbian",
                "name":        "長鞭",
                "type":        "尋",
                "bonus":       79,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/changbian.c",
        ]),
        ([
                "id":          "fu chen",
                "name":        "拂塵",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/fuchen.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "[1;37m白色長衫[2;37;0m",
                "type":        "尋",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/cloth4.c",
        ]),
        ([
                "id":          "chang pao",
                "name":        "白色長袍",
                "type":        "尋",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/baituo/obj/baipao.c",
        ]),
        ([
                "id":          "diao gan",
                "name":        "釣杆",
                "type":        "尋",
                "bonus":       77,
                "msg1":        "",
                "object":      "/kungfu/class/dali/obj/diaogan.c",
        ]),
});
mapping query_questsn()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
