#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "jiuyi daoren",
                "name":        "九翼道人",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/lingjiu/npc/jiuyi.c",
        ]),
        ([
                "id":          "wu santong",
                "name":        "武三通",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wusantong.c",
        ]),
        ([
                "id":          "wang bashuai",
                "name":        "王八衰",
                "type":        "殺",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/wang8.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "媒婆",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/suzhou/npc/meipo.c",
        ]),
        ([
                "id":          "sha tianjiang",
                "name":        "沙天江",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/songshan/npc/sha.c",
        ]),
        ([
                "id":          "yue lingshan",
                "name":        "嶽靈珊",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huashan/npc/yue-lingshan.c",
        ]),
        ([
                "id":          "hou tonghai",
                "name":        "侯通海",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huanghe/npc/hou.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "白衣武士",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi1.c",
        ]),
        ([
                "id":          "di xiu",
                "name":        "狄修",
                "type":        "殺",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/songshan/di.c",
        ]),
        ([
                "id":          "yu renhao",
                "name":        "於人豪",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/yu.c",
        ]),
        ([
                "id":          "san hu",
                "name":        "忽倫三虎",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sanhu.c",
        ]),
        ([
                "id":          "jiao wenqi",
                "name":        "焦文期",
                "type":        "殺",
                "bonus":       99,
                "msg":        "",
                "object":      "/d/guanwai/npc/jiaowenqi.c",
        ]),
        ([
                "id":          "zu qianqiu",
                "name":        "祖千秋",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huanghe/npc/zu.c",
        ]),
        ([
                "id":          "er hu",
                "name":        "忽倫二虎",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/erhu.c",
        ]),
        ([
                "id":          "da hu",
                "name":        "忽倫大虎",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/dahu.c",
        ]),
        ([
                "id":          "bo chen",
                "name":        "卜沉",
                "type":        "殺",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/songshan/npc/bo.c",
        ]),
        ([
                "id":          "lao denuo",
                "name":        "勞德諾",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/huashan/npc/lao-denuo.c",
        ]),
        ([
                "id":          "sun popo",
                "name":        "孫婆婆",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/gumu/npc/sun.c",
        ]),
        ([
                "id":          "hong renxiong",
                "name":        "洪人雄",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/hong.c",
        ]),
        ([
                "id":          "song qingshu",
                "name":        "宋青書",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/emei/npc/songqingshu.c",
        ]),
        ([
                "id":          "wu xiuwen",
                "name":        "武修文",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wuxiuwen.c",
        ]),
        ([
                "id":          "zhou wushu",
                "name":        "週五輸",
                "type":        "殺",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhou5.c",
        ]),
        ([
                "id":          "zheng qimie",
                "name":        "鄭七滅",
                "type":        "殺",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zheng7.c",
        ]),
        ([
                "id":          "lu bai",
                "name":        "陸柏",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/songshan/npc/lu.c",
        ]),
        ([
                "id":          "gao kexin",
                "name":        "高克新",
                "type":        "殺",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/songshan/npc/gao.c",
        ]),
        ([
                "id":          "sun sanhui",
                "name":        "孫三毀",
                "type":        "殺",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/sun3.c",
        ]),
        ([
                "id":          "yuji zi",
                "name":        "玉璣子",
                "type":        "殺",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yujizi.c",
        ]),
        ([
                "id":          "zhong zhen",
                "name":        "鍾鎮",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/songshan/npc/zhong.c",
        ]),
        ([
                "id":          "luo renjie",
                "name":        "羅人傑",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/luo.c",
        ]),
        ([
                "id":          "zhu ziliu",
                "name":        "朱子柳",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/zhuziliu.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "紅衣武士",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi2.c",
        ]),
        ([
                "id":          "li kexiu",
                "name":        "李可秀",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/hangzhou/npc/likexiu.c",
        ]),
        ([
                "id":          "si hu",
                "name":        "忽倫四虎",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sihu.c",
        ]),
        ([
                "id":          "yuqing zi",
                "name":        "玉磬子",
                "type":        "殺",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yuqingzi.c",
        ]),
        ([
                "id":          "ding mian",
                "name":        "丁勉",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/songshan/npc/ding.c",
        ]),
        ([
                "id":          "huo renying",
                "name":        "侯人英",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/hou.c",
        ]),
        ([
                "id":          "hu qingniu",
                "name":        "胡青牛",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/mingjiao/npc/hu.c",
        ]),
        ([
                "id":          "li si",
                "name":        "李四",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/village/npc/xiejian.c",
        ]),
        ([
                "id":          "zhao yishang",
                "name":        "趙一傷",
                "type":        "殺",
                "bonus":       62,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhao1.c",
        ]),
        ([
                "id":          "li sicui",
                "name":        "李四摧",
                "type":        "殺",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/li4.c",
        ]),
        ([
                "id":          "yuyin zi",
                "name":        "玉音子",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yuyinzi.c",
        ]),
        ([
                "id":          "tang yinghu",
                "name":        "湯英鵠",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/songshan/npc/tang.c",
        ]),
        ([
                "id":          "ping si",
                "name":        "平四",
                "type":        "殺",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/hu/pingsi.c",
        ]),
        ([
                "id":          "huo xiansheng",
                "name":        "霍先生",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/dali/npc/huo.c",
        ]),
        ([
                "id":          "yulin jun",
                "name":        "御林軍",
                "type":        "殺",
                "bonus":       95,
                "msg":        "",
                "object":      "/d/changan/npc/yulinjun.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "武將",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/wujiang.c",
        ]),
        ([
                "id":          "murong hao",
                "name":        "慕容豪",
                "type":        "殺",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/changan/npc/murong-hao.c",
        ]),
        ([
                "id":          "da shou",
                "name":        "打手",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/dashou.c",
        ]),
        ([
                "id":          "bao biao",
                "name":        "群玉樓保鏢",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/baobiao.c",
        ]),
        ([
                "id":          "gongtangcang guoshi",
                "name":        "貢唐倉國師",
                "type":        "殺",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/guoshi.c",
        ]),
        ([
                "id":          "shan yong",
                "name":        "善勇",
                "type":        "殺",
                "bonus":       61,
                "msg":        "",
                "object":      "/kungfu/class/xuedao/shanyong.c",
        ]),
        ([
                "id":          "xue muhua",
                "name":        "薛慕華",
                "type":        "殺",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/xuemuh.c",
        ]),
        ([
                "id":          "zhao zhijing",
                "name":        "趙志敬",
                "type":        "殺",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/zhao.c",
        ]),
        ([
                "id":          "kuai huosan",
                "name":        "快活三",
                "type":        "殺",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/kuai-huosan.c",
        ]),
        ([
                "id":          "jiang shangyou",
                "name":        "江上游",
                "type":        "殺",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/jiang-sy.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "媒婆",
                "type":        "殺",
                "bonus":       71,
                "msg":        "",
                "object":      "/adm/npc/meipo.c",
        ]),
});
mapping query_questsn()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
